; Song Untitled, in AKY version 1.0, generated by Arkos Tracker 2.

music_Subsong0
music_Subsong0DisarkGenerateExternalLabel

; Header
music_Subsong0DisarkByteRegionStart0
	db 128	; Format version: 0 and endianness: little-endian.
	db 3	; How many channels are encoded.
; Frequency of the PSG index 0: 1000000Hz.
	db 64, 66, 15, 0
music_Subsong0DisarkByteRegionEnd0

music_Subsong0_Linker
music_Subsong0DisarkPointerRegionStart1
; Pattern 0
music_Subsong0_LinkerLoop	; Loops here.
music_Subsong0DisarkWordForceNonReference2
	dw 256	; Duration in frames.
	dw music_Subsong0_Track_0
	dw music_Subsong0_Track_13
	dw music_Subsong0_Track_5

; Pattern 1
music_Subsong0DisarkWordForceNonReference3
	dw 256	; Duration in frames.
	dw music_Subsong0_Track_12
	dw music_Subsong0_Track_13
	dw music_Subsong0_Track_5

; Pattern 2
music_Subsong0DisarkWordForceNonReference4
	dw 256	; Duration in frames.
	dw music_Subsong0_Track_6
	dw music_Subsong0_Track_13
	dw music_Subsong0_Track_8

; Pattern 3
music_Subsong0DisarkWordForceNonReference5
	dw 256	; Duration in frames.
	dw music_Subsong0_Track_9
	dw music_Subsong0_Track_13
	dw music_Subsong0_Track_11

; Pattern 4
music_Subsong0DisarkWordForceNonReference6
	dw 256	; Duration in frames.
	dw music_Subsong0_Track_12
	dw music_Subsong0_Track_13
	dw music_Subsong0_Track_14

; Pattern 5
music_Subsong0DisarkWordForceNonReference7
	dw 256	; Duration in frames.
	dw music_Subsong0_Track_15
	dw music_Subsong0_Track_16
	dw music_Subsong0_Track_17

music_Subsong0DisarkWordForceNonReference8
	dw 0	; Loops (duration = 0).
	dw music_Subsong0_LinkerLoop
music_Subsong0DisarkPointerRegionEnd1

; The tracks.
music_Subsong0_Track_0
music_Subsong0DisarkByteRegionStart9
	db 64	; Duration.
music_Subsong0DisarkByteRegionEnd9
music_Subsong0DisarkPointerRegionStart10
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd10

music_Subsong0DisarkByteRegionStart11
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd11
music_Subsong0DisarkPointerRegionStart12
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd12

music_Subsong0DisarkByteRegionStart13
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd13
music_Subsong0DisarkPointerRegionStart14
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd14

music_Subsong0DisarkByteRegionStart15
	db 80	; Duration.
music_Subsong0DisarkByteRegionEnd15
music_Subsong0DisarkPointerRegionStart16
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd16

music_Subsong0DisarkByteRegionStart17
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd17
music_Subsong0DisarkPointerRegionStart18
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd18

music_Subsong0DisarkByteRegionStart19
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd19
music_Subsong0DisarkPointerRegionStart20
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd20

music_Subsong0DisarkByteRegionStart21
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd21
music_Subsong0DisarkPointerRegionStart22
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd22

music_Subsong0DisarkByteRegionStart23
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd23
music_Subsong0DisarkPointerRegionStart24
	dw music_Subsong0_RegisterBlock_7
music_Subsong0DisarkPointerRegionEnd24

music_Subsong0_Track_5
music_Subsong0DisarkByteRegionStart25
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd25
music_Subsong0DisarkPointerRegionStart26
	dw music_Subsong0_RegisterBlock_9
music_Subsong0DisarkPointerRegionEnd26

music_Subsong0DisarkByteRegionStart27
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd27
music_Subsong0DisarkPointerRegionStart28
	dw music_Subsong0_RegisterBlock_10
music_Subsong0DisarkPointerRegionEnd28

music_Subsong0DisarkByteRegionStart29
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd29
music_Subsong0DisarkPointerRegionStart30
	dw music_Subsong0_RegisterBlock_11
music_Subsong0DisarkPointerRegionEnd30

music_Subsong0DisarkByteRegionStart31
	db 128	; Duration.
music_Subsong0DisarkByteRegionEnd31
music_Subsong0DisarkPointerRegionStart32
	dw music_Subsong0_RegisterBlock_78
music_Subsong0DisarkPointerRegionEnd32

music_Subsong0_Track_6
music_Subsong0DisarkByteRegionStart33
	db 64	; Duration.
music_Subsong0DisarkByteRegionEnd33
music_Subsong0DisarkPointerRegionStart34
	dw music_Subsong0_RegisterBlock_17
music_Subsong0DisarkPointerRegionEnd34

music_Subsong0DisarkByteRegionStart35
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd35
music_Subsong0DisarkPointerRegionStart36
	dw music_Subsong0_RegisterBlock_17
music_Subsong0DisarkPointerRegionEnd36

music_Subsong0DisarkByteRegionStart37
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd37
music_Subsong0DisarkPointerRegionStart38
	dw music_Subsong0_RegisterBlock_17
music_Subsong0DisarkPointerRegionEnd38

music_Subsong0DisarkByteRegionStart39
	db 80	; Duration.
music_Subsong0DisarkByteRegionEnd39
music_Subsong0DisarkPointerRegionStart40
	dw music_Subsong0_RegisterBlock_17
music_Subsong0DisarkPointerRegionEnd40

music_Subsong0DisarkByteRegionStart41
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd41
music_Subsong0DisarkPointerRegionStart42
	dw music_Subsong0_RegisterBlock_17
music_Subsong0DisarkPointerRegionEnd42

music_Subsong0DisarkByteRegionStart43
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd43
music_Subsong0DisarkPointerRegionStart44
	dw music_Subsong0_RegisterBlock_17
music_Subsong0DisarkPointerRegionEnd44

music_Subsong0DisarkByteRegionStart45
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd45
music_Subsong0DisarkPointerRegionStart46
	dw music_Subsong0_RegisterBlock_17
music_Subsong0DisarkPointerRegionEnd46

music_Subsong0DisarkByteRegionStart47
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd47
music_Subsong0DisarkPointerRegionStart48
	dw music_Subsong0_RegisterBlock_21
music_Subsong0DisarkPointerRegionEnd48

music_Subsong0_Track_8
music_Subsong0DisarkByteRegionStart49
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd49
music_Subsong0DisarkPointerRegionStart50
	dw music_Subsong0_RegisterBlock_9
music_Subsong0DisarkPointerRegionEnd50

music_Subsong0DisarkByteRegionStart51
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd51
music_Subsong0DisarkPointerRegionStart52
	dw music_Subsong0_RegisterBlock_10
music_Subsong0DisarkPointerRegionEnd52

music_Subsong0DisarkByteRegionStart53
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd53
music_Subsong0DisarkPointerRegionStart54
	dw music_Subsong0_RegisterBlock_11
music_Subsong0DisarkPointerRegionEnd54

music_Subsong0DisarkByteRegionStart55
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd55
music_Subsong0DisarkPointerRegionStart56
	dw music_Subsong0_RegisterBlock_26
music_Subsong0DisarkPointerRegionEnd56

music_Subsong0DisarkByteRegionStart57
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd57
music_Subsong0DisarkPointerRegionStart58
	dw music_Subsong0_RegisterBlock_27
music_Subsong0DisarkPointerRegionEnd58

music_Subsong0DisarkByteRegionStart59
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd59
music_Subsong0DisarkPointerRegionStart60
	dw music_Subsong0_RegisterBlock_11
music_Subsong0DisarkPointerRegionEnd60

music_Subsong0DisarkByteRegionStart61
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd61
music_Subsong0DisarkPointerRegionStart62
	dw music_Subsong0_RegisterBlock_29
music_Subsong0DisarkPointerRegionEnd62

music_Subsong0DisarkByteRegionStart63
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd63
music_Subsong0DisarkPointerRegionStart64
	dw music_Subsong0_RegisterBlock_10
music_Subsong0DisarkPointerRegionEnd64

music_Subsong0DisarkByteRegionStart65
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd65
music_Subsong0DisarkPointerRegionStart66
	dw music_Subsong0_RegisterBlock_9
music_Subsong0DisarkPointerRegionEnd66

music_Subsong0_Track_9
music_Subsong0DisarkByteRegionStart67
	db 64	; Duration.
music_Subsong0DisarkByteRegionEnd67
music_Subsong0DisarkPointerRegionStart68
	dw music_Subsong0_RegisterBlock_36
music_Subsong0DisarkPointerRegionEnd68

music_Subsong0DisarkByteRegionStart69
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd69
music_Subsong0DisarkPointerRegionStart70
	dw music_Subsong0_RegisterBlock_36
music_Subsong0DisarkPointerRegionEnd70

music_Subsong0DisarkByteRegionStart71
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd71
music_Subsong0DisarkPointerRegionStart72
	dw music_Subsong0_RegisterBlock_36
music_Subsong0DisarkPointerRegionEnd72

music_Subsong0DisarkByteRegionStart73
	db 80	; Duration.
music_Subsong0DisarkByteRegionEnd73
music_Subsong0DisarkPointerRegionStart74
	dw music_Subsong0_RegisterBlock_36
music_Subsong0DisarkPointerRegionEnd74

music_Subsong0DisarkByteRegionStart75
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd75
music_Subsong0DisarkPointerRegionStart76
	dw music_Subsong0_RegisterBlock_36
music_Subsong0DisarkPointerRegionEnd76

music_Subsong0DisarkByteRegionStart77
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd77
music_Subsong0DisarkPointerRegionStart78
	dw music_Subsong0_RegisterBlock_36
music_Subsong0DisarkPointerRegionEnd78

music_Subsong0DisarkByteRegionStart79
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd79
music_Subsong0DisarkPointerRegionStart80
	dw music_Subsong0_RegisterBlock_40
music_Subsong0DisarkPointerRegionEnd80

music_Subsong0DisarkByteRegionStart81
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd81
music_Subsong0DisarkPointerRegionStart82
	dw music_Subsong0_RegisterBlock_40
music_Subsong0DisarkPointerRegionEnd82

music_Subsong0_Track_11
music_Subsong0DisarkByteRegionStart83
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd83
music_Subsong0DisarkPointerRegionStart84
	dw music_Subsong0_RegisterBlock_9
music_Subsong0DisarkPointerRegionEnd84

music_Subsong0DisarkByteRegionStart85
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd85
music_Subsong0DisarkPointerRegionStart86
	dw music_Subsong0_RegisterBlock_10
music_Subsong0DisarkPointerRegionEnd86

music_Subsong0DisarkByteRegionStart87
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd87
music_Subsong0DisarkPointerRegionStart88
	dw music_Subsong0_RegisterBlock_11
music_Subsong0DisarkPointerRegionEnd88

music_Subsong0DisarkByteRegionStart89
	db 48	; Duration.
music_Subsong0DisarkByteRegionEnd89
music_Subsong0DisarkPointerRegionStart90
	dw music_Subsong0_RegisterBlock_26
music_Subsong0DisarkPointerRegionEnd90

music_Subsong0DisarkByteRegionStart91
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd91
music_Subsong0DisarkPointerRegionStart92
	dw music_Subsong0_RegisterBlock_27
music_Subsong0DisarkPointerRegionEnd92

music_Subsong0DisarkByteRegionStart93
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd93
music_Subsong0DisarkPointerRegionStart94
	dw music_Subsong0_RegisterBlock_11
music_Subsong0DisarkPointerRegionEnd94

music_Subsong0DisarkByteRegionStart95
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd95
music_Subsong0DisarkPointerRegionStart96
	dw music_Subsong0_RegisterBlock_27
music_Subsong0DisarkPointerRegionEnd96

music_Subsong0DisarkByteRegionStart97
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd97
music_Subsong0DisarkPointerRegionStart98
	dw music_Subsong0_RegisterBlock_29
music_Subsong0DisarkPointerRegionEnd98

music_Subsong0DisarkByteRegionStart99
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd99
music_Subsong0DisarkPointerRegionStart100
	dw music_Subsong0_RegisterBlock_11
music_Subsong0DisarkPointerRegionEnd100

music_Subsong0_Track_12
music_Subsong0DisarkByteRegionStart101
	db 64	; Duration.
music_Subsong0DisarkByteRegionEnd101
music_Subsong0DisarkPointerRegionStart102
	dw music_Subsong0_RegisterBlock_55
music_Subsong0DisarkPointerRegionEnd102

music_Subsong0DisarkByteRegionStart103
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd103
music_Subsong0DisarkPointerRegionStart104
	dw music_Subsong0_RegisterBlock_55
music_Subsong0DisarkPointerRegionEnd104

music_Subsong0DisarkByteRegionStart105
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd105
music_Subsong0DisarkPointerRegionStart106
	dw music_Subsong0_RegisterBlock_55
music_Subsong0DisarkPointerRegionEnd106

music_Subsong0DisarkByteRegionStart107
	db 80	; Duration.
music_Subsong0DisarkByteRegionEnd107
music_Subsong0DisarkPointerRegionStart108
	dw music_Subsong0_RegisterBlock_55
music_Subsong0DisarkPointerRegionEnd108

music_Subsong0DisarkByteRegionStart109
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd109
music_Subsong0DisarkPointerRegionStart110
	dw music_Subsong0_RegisterBlock_55
music_Subsong0DisarkPointerRegionEnd110

music_Subsong0DisarkByteRegionStart111
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd111
music_Subsong0DisarkPointerRegionStart112
	dw music_Subsong0_RegisterBlock_55
music_Subsong0DisarkPointerRegionEnd112

music_Subsong0DisarkByteRegionStart113
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd113
music_Subsong0DisarkPointerRegionStart114
	dw music_Subsong0_RegisterBlock_55
music_Subsong0DisarkPointerRegionEnd114

music_Subsong0DisarkByteRegionStart115
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd115
music_Subsong0DisarkPointerRegionStart116
	dw music_Subsong0_RegisterBlock_36
music_Subsong0DisarkPointerRegionEnd116

music_Subsong0_Track_13
music_Subsong0DisarkByteRegionStart117
	db 24	; Duration.
music_Subsong0DisarkByteRegionEnd117
music_Subsong0DisarkPointerRegionStart118
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd118

music_Subsong0DisarkByteRegionStart119
	db 8	; Duration.
music_Subsong0DisarkByteRegionEnd119
music_Subsong0DisarkPointerRegionStart120
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd120

music_Subsong0DisarkByteRegionStart121
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd121
music_Subsong0DisarkPointerRegionStart122
	dw music_Subsong0_RegisterBlock_67
music_Subsong0DisarkPointerRegionEnd122

music_Subsong0DisarkByteRegionStart123
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd123
music_Subsong0DisarkPointerRegionStart124
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd124

music_Subsong0DisarkByteRegionStart125
	db 24	; Duration.
music_Subsong0DisarkByteRegionEnd125
music_Subsong0DisarkPointerRegionStart126
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd126

music_Subsong0DisarkByteRegionStart127
	db 8	; Duration.
music_Subsong0DisarkByteRegionEnd127
music_Subsong0DisarkPointerRegionStart128
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd128

music_Subsong0DisarkByteRegionStart129
	db 32	; Duration.
music_Subsong0DisarkByteRegionEnd129
music_Subsong0DisarkPointerRegionStart130
	dw music_Subsong0_RegisterBlock_67
music_Subsong0DisarkPointerRegionEnd130

music_Subsong0DisarkByteRegionStart131
	db 24	; Duration.
music_Subsong0DisarkByteRegionEnd131
music_Subsong0DisarkPointerRegionStart132
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd132

music_Subsong0DisarkByteRegionStart133
	db 8	; Duration.
music_Subsong0DisarkByteRegionEnd133
music_Subsong0DisarkPointerRegionStart134
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd134

music_Subsong0DisarkByteRegionStart135
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd135
music_Subsong0DisarkPointerRegionStart136
	dw music_Subsong0_RegisterBlock_67
music_Subsong0DisarkPointerRegionEnd136

music_Subsong0DisarkByteRegionStart137
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd137
music_Subsong0DisarkPointerRegionStart138
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd138

music_Subsong0DisarkByteRegionStart139
	db 24	; Duration.
music_Subsong0DisarkByteRegionEnd139
music_Subsong0DisarkPointerRegionStart140
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd140

music_Subsong0DisarkByteRegionStart141
	db 8	; Duration.
music_Subsong0DisarkByteRegionEnd141
music_Subsong0DisarkPointerRegionStart142
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd142

music_Subsong0DisarkByteRegionStart143
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd143
music_Subsong0DisarkPointerRegionStart144
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd144

music_Subsong0DisarkByteRegionStart145
	db 8	; Duration.
music_Subsong0DisarkByteRegionEnd145
music_Subsong0DisarkPointerRegionStart146
	dw music_Subsong0_RegisterBlock_61
music_Subsong0DisarkPointerRegionEnd146

music_Subsong0DisarkByteRegionStart147
	db 8	; Duration.
music_Subsong0DisarkByteRegionEnd147
music_Subsong0DisarkPointerRegionStart148
	dw music_Subsong0_RegisterBlock_67
music_Subsong0DisarkPointerRegionEnd148

music_Subsong0_Track_14
music_Subsong0DisarkByteRegionStart149
	db 176	; Duration.
music_Subsong0DisarkByteRegionEnd149
music_Subsong0DisarkPointerRegionStart150
	dw music_Subsong0_RegisterBlock_78
music_Subsong0DisarkPointerRegionEnd150

music_Subsong0DisarkByteRegionStart151
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd151
music_Subsong0DisarkPointerRegionStart152
	dw music_Subsong0_RegisterBlock_27
music_Subsong0DisarkPointerRegionEnd152

music_Subsong0DisarkByteRegionStart153
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd153
music_Subsong0DisarkPointerRegionStart154
	dw music_Subsong0_RegisterBlock_11
music_Subsong0DisarkPointerRegionEnd154

music_Subsong0DisarkByteRegionStart155
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd155
music_Subsong0DisarkPointerRegionStart156
	dw music_Subsong0_RegisterBlock_27
music_Subsong0DisarkPointerRegionEnd156

music_Subsong0DisarkByteRegionStart157
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd157
music_Subsong0DisarkPointerRegionStart158
	dw music_Subsong0_RegisterBlock_29
music_Subsong0DisarkPointerRegionEnd158

music_Subsong0DisarkByteRegionStart159
	db 16	; Duration.
music_Subsong0DisarkByteRegionEnd159
music_Subsong0DisarkPointerRegionStart160
	dw music_Subsong0_RegisterBlock_10
music_Subsong0DisarkPointerRegionEnd160

music_Subsong0_Track_15
music_Subsong0DisarkByteRegionStart161
	db 128	; Duration.
music_Subsong0DisarkByteRegionEnd161
music_Subsong0DisarkPointerRegionStart162
	dw music_Subsong0_RegisterBlock_85
music_Subsong0DisarkPointerRegionEnd162

music_Subsong0DisarkByteRegionStart163
	db 128	; Duration.
music_Subsong0DisarkByteRegionEnd163
music_Subsong0DisarkPointerRegionStart164
	dw music_Subsong0_RegisterBlock_86
music_Subsong0DisarkPointerRegionEnd164

music_Subsong0_Track_16
music_Subsong0DisarkByteRegionStart165
	db 255	; Duration.
music_Subsong0DisarkByteRegionEnd165
music_Subsong0DisarkPointerRegionStart166
	dw music_Subsong0_RegisterBlock_88
music_Subsong0DisarkPointerRegionEnd166

music_Subsong0DisarkByteRegionStart167
	db 1	; Duration.
music_Subsong0DisarkByteRegionEnd167
music_Subsong0DisarkPointerRegionStart168
	dw music_Subsong0_RegisterBlock_88
music_Subsong0DisarkPointerRegionEnd168

music_Subsong0_Track_17
music_Subsong0DisarkByteRegionStart169
	db 64	; Duration.
music_Subsong0DisarkByteRegionEnd169
music_Subsong0DisarkPointerRegionStart170
	dw music_Subsong0_RegisterBlock_78
music_Subsong0DisarkPointerRegionEnd170

music_Subsong0DisarkByteRegionStart171
	db 192	; Duration.
music_Subsong0DisarkByteRegionEnd171
music_Subsong0DisarkPointerRegionStart172
	dw music_Subsong0_RegisterBlock_88
music_Subsong0DisarkPointerRegionEnd172


; The RegisterBlocks.
music_Subsong0DisarkByteRegionStart173
music_Subsong0_RegisterBlock_88
	db 0	; Initial State: no software, no hardware.

music_Subsong0_RegisterBlock_88_Loop
	db 4	; Non-initial State, no software no hardware.

	db 8	; Loop to index 1.
music_Subsong0DisarkPointerRegionStart174
	dw music_Subsong0_RegisterBlock_88_Loop
music_Subsong0DisarkPointerRegionEnd174


music_Subsong0_RegisterBlock_78
	db 113	; Initial State: software only.
	db 119, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 105	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 101	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 1	; Non-initial State, software only.

music_Subsong0_RegisterBlock_78_Loop
	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 93	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 89	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 8	; Loop to index 20.
music_Subsong0DisarkPointerRegionStart175
	dw music_Subsong0_RegisterBlock_78_Loop
music_Subsong0DisarkPointerRegionEnd175


music_Subsong0_RegisterBlock_12
	db 113	; Initial State: software only.
	db 119, 0	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart176
	dw music_Subsong0_RegisterBlock_78 + 3	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd176

music_Subsong0_RegisterBlock_85
	db 121	; Initial State: software only.
	db 188, 3	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

music_Subsong0_RegisterBlock_85_Loop
	db 225	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
music_Subsong0DisarkPointerRegionStart177
	dw music_Subsong0_RegisterBlock_85_Loop
music_Subsong0DisarkPointerRegionEnd177


music_Subsong0_RegisterBlock_86
	db 121	; Initial State: software only.
	db 119, 7	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 119	; New LSB for software period.
	db 7	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 119	; New LSB for software period.
	db 7	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 119	; New LSB for software period.
	db 7	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 119	; New LSB for software period.
	db 7	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 119	; New LSB for software period.
	db 7	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 119	; New LSB for software period.
	db 7	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

music_Subsong0_RegisterBlock_86_Loop
	db 225	; Non-initial State, software only.
	db 119	; New LSB for software period.
	db 7	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
music_Subsong0DisarkPointerRegionStart178
	dw music_Subsong0_RegisterBlock_86_Loop
music_Subsong0DisarkPointerRegionEnd178


music_Subsong0_RegisterBlock_3
	db 121	; Initial State: software only.
	db 188, 3	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart179
	dw music_Subsong0_RegisterBlock_85 + 3	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd179

music_Subsong0_RegisterBlock_17
	db 121	; Initial State: software only.
	db 152, 5	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 152	; New LSB for software period.
	db 5	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 152	; New LSB for software period.
	db 5	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 152	; New LSB for software period.
	db 5	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 152	; New LSB for software period.
	db 5	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 152	; New LSB for software period.
	db 5	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 152	; New LSB for software period.
	db 5	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

music_Subsong0_RegisterBlock_17_Loop
	db 225	; Non-initial State, software only.
	db 152	; New LSB for software period.
	db 5	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
music_Subsong0DisarkPointerRegionStart180
	dw music_Subsong0_RegisterBlock_17_Loop
music_Subsong0DisarkPointerRegionEnd180


music_Subsong0_RegisterBlock_36
	db 121	; Initial State: software only.
	db 49, 4	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 49	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 49	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 49	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 49	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 49	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 49	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

music_Subsong0_RegisterBlock_36_Loop
	db 225	; Non-initial State, software only.
	db 49	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 24	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
music_Subsong0DisarkPointerRegionStart181
	dw music_Subsong0_RegisterBlock_36_Loop
music_Subsong0DisarkPointerRegionEnd181


music_Subsong0_RegisterBlock_55
	db 121	; Initial State: software only.
	db 180, 4	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 180	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 180	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 180	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 180	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 180	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 180	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

music_Subsong0_RegisterBlock_55_Loop
	db 225	; Non-initial State, software only.
	db 180	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 90	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
music_Subsong0DisarkPointerRegionStart182
	dw music_Subsong0_RegisterBlock_55_Loop
music_Subsong0DisarkPointerRegionEnd182


music_Subsong0_RegisterBlock_0
	db 121	; Initial State: software only.
	db 188, 3	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart183
	dw music_Subsong0_RegisterBlock_85 + 3	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd183

music_Subsong0_RegisterBlock_14
	db 121	; Initial State: software only.
	db 152, 5	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart184
	dw music_Subsong0_RegisterBlock_17 + 3	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd184

music_Subsong0_RegisterBlock_33
	db 121	; Initial State: software only.
	db 49, 4	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart185
	dw music_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd185

music_Subsong0_RegisterBlock_52
	db 121	; Initial State: software only.
	db 180, 4	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart186
	dw music_Subsong0_RegisterBlock_55 + 3	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd186

music_Subsong0_RegisterBlock_9
	db 113	; Initial State: software only.
	db 106, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 53	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 106	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 105	; Non-initial State, software only.
	db 53	; New LSB for software period.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 101	; Non-initial State, software only.
	db 106	; New LSB for software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 53	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 106	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 53	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

music_Subsong0_RegisterBlock_9_Loop
	db 93	; Non-initial State, software only.
	db 106	; New LSB for software period.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 89	; Non-initial State, software only.
	db 53	; New LSB for software period.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 106	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 53	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 24.
music_Subsong0DisarkPointerRegionStart187
	dw music_Subsong0_RegisterBlock_9_Loop
music_Subsong0DisarkPointerRegionEnd187


music_Subsong0_RegisterBlock_10
	db 113	; Initial State: software only.
	db 100, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 50	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 100	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 105	; Non-initial State, software only.
	db 50	; New LSB for software period.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 101	; Non-initial State, software only.
	db 100	; New LSB for software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 50	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 100	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 50	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

music_Subsong0_RegisterBlock_10_Loop
	db 93	; Non-initial State, software only.
	db 100	; New LSB for software period.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 89	; Non-initial State, software only.
	db 50	; New LSB for software period.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 100	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 50	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 24.
music_Subsong0DisarkPointerRegionStart188
	dw music_Subsong0_RegisterBlock_10_Loop
music_Subsong0DisarkPointerRegionEnd188


music_Subsong0_RegisterBlock_26
	db 113	; Initial State: software only.
	db 60, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 30	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 105	; Non-initial State, software only.
	db 30	; New LSB for software period.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 101	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 30	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 30	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

music_Subsong0_RegisterBlock_26_Loop
	db 93	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 89	; Non-initial State, software only.
	db 30	; New LSB for software period.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 60	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 30	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 24.
music_Subsong0DisarkPointerRegionStart189
	dw music_Subsong0_RegisterBlock_26_Loop
music_Subsong0DisarkPointerRegionEnd189


music_Subsong0_RegisterBlock_7
	db 121	; Initial State: software only.
	db 83, 3	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 83	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 83	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 83	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 83	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 83	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 83	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 83	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 170	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.


music_Subsong0_RegisterBlock_11
	db 113	; Initial State: software only.
	db 80, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 40	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 80	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 105	; Non-initial State, software only.
	db 40	; New LSB for software period.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 101	; Non-initial State, software only.
	db 80	; New LSB for software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 40	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 80	; New LSB for software period.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 40	; New LSB for software period.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 93	; Non-initial State, software only.
	db 80	; New LSB for software period.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 89	; Non-initial State, software only.
	db 40	; New LSB for software period.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 65	; Non-initial State, software only.
	db 80	; New LSB for software period.

	db 1	; Non-initial State, software only.


music_Subsong0_RegisterBlock_21
	db 121	; Initial State: software only.
	db 252, 4	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.


music_Subsong0_RegisterBlock_40
	db 121	; Initial State: software only.
	db 244, 3	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 244	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 244	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 244	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 244	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 244	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 244	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 244	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 250	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.


music_Subsong0_RegisterBlock_67
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 222, 1	; Software period.

	db 241	; Non-initial State, software only.
	db 206	; New LSB for software period.
	db 129	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 158	; New LSB for software period.
	db 193	; New MSB for software period, maybe with noise.
	db 15	; New noise.

	db 8
music_Subsong0DisarkPointerRegionStart190
	dw music_Subsong0_RegisterBlock_88 + 1	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd190

music_Subsong0_RegisterBlock_61
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 188, 3	; Software period.

	db 241	; Non-initial State, software only.
	db 172	; New LSB for software period.
	db 131	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 124	; New LSB for software period.
	db 195	; New MSB for software period, maybe with noise.
	db 15	; New noise.

	db 8
music_Subsong0DisarkPointerRegionStart191
	dw music_Subsong0_RegisterBlock_88 + 1	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd191

music_Subsong0_RegisterBlock_27
	db 113	; Initial State: software only.
	db 67, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 34	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 67	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 105	; Non-initial State, software only.
	db 34	; New LSB for software period.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 101	; Non-initial State, software only.
	db 67	; New LSB for software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 34	; New LSB for software period.


music_Subsong0_RegisterBlock_29
	db 113	; Initial State: software only.
	db 89, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 45	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 89	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 105	; Non-initial State, software only.
	db 45	; New LSB for software period.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 101	; Non-initial State, software only.
	db 89	; New LSB for software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 97	; Non-initial State, software only.
	db 45	; New LSB for software period.


music_Subsong0_RegisterBlock_39
	db 121	; Initial State: software only.
	db 244, 3	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart192
	dw music_Subsong0_RegisterBlock_40 + 3	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd192

music_Subsong0_RegisterBlock_63
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 222, 1	; Software period.

	db 8
music_Subsong0DisarkPointerRegionStart193
	dw music_Subsong0_RegisterBlock_67 + 4	; Optimization: goto common Block at index 1.
music_Subsong0DisarkPointerRegionEnd193

music_Subsong0DisarkByteRegionEnd173
