; Sound Effects for song effet, version 2.0, generated by Arkos Tracker 2.

effet_SoundEffects
effet_SoundEffectsDisarkGenerateExternalLabel

; The sound effects, starting at 1.
effet_SoundEffectsDisarkPointerRegionStart0
	dw effet_SoundEffects_Sound1	; Sound effect 1.
	dw effet_SoundEffects_Sound2	; Sound effect 2.
effet_SoundEffectsDisarkPointerRegionEnd0

effet_SoundEffectsDisarkByteRegionStart1
; Sound effect 1.
effet_SoundEffects_Sound1
	db 4	; Speed

effet_SoundEffects_Sound1_Loop	db 160	; No soft, no hard. Volume: 4.
	db 7	; Noise: 7.

	db 168	; No soft, no hard. Volume: 5.
	db 7	; Noise: 7.

	db 176	; No soft, no hard. Volume: 6.
	db 7	; Noise: 7.

	db 184	; No soft, no hard. Volume: 7.
	db 7	; Noise: 7.

	db 192	; No soft, no hard. Volume: 8.
	db 7	; Noise: 7.

	db 200	; No soft, no hard. Volume: 9.
	db 7	; Noise: 7.

	db 208	; No soft, no hard. Volume: 10.
	db 7	; Noise: 7.

	db 216	; No soft, no hard. Volume: 11.
	db 7	; Noise: 7.

	db 224	; No soft, no hard. Volume: 12.
	db 7	; Noise: 7.

	db 232	; No soft, no hard. Volume: 13.
	db 7	; Noise: 7.

	db 240	; No soft, no hard. Volume: 14.
	db 7	; Noise: 7.

	db 232	; No soft, no hard. Volume: 13.
	db 7	; Noise: 7.

	db 224	; No soft, no hard. Volume: 12.
	db 7	; Noise: 7.

	db 216	; No soft, no hard. Volume: 11.
	db 7	; Noise: 7.

	db 208	; No soft, no hard. Volume: 10.
	db 7	; Noise: 7.

	db 200	; No soft, no hard. Volume: 9.
	db 7	; Noise: 7.

	db 192	; No soft, no hard. Volume: 8.
	db 7	; Noise: 7.

	db 184	; No soft, no hard. Volume: 7.
	db 7	; Noise: 7.

	db 176	; No soft, no hard. Volume: 6.
	db 7	; Noise: 7.

	db 168	; No soft, no hard. Volume: 5.
	db 7	; Noise: 7.

	db 4	; End of the sound effect.

; Sound effect 2.
effet_SoundEffects_Sound2
	db 0	; Speed

effet_SoundEffects_Sound2_Loop	db 248	; No soft, no hard. Volume: 15.
	db 1	; Noise: 1.

	db 4	; End of the sound effect.

effet_SoundEffectsDisarkByteRegionEnd1
