; Song Untitled, in AKY version 1.0, generated by Arkos Tracker 2.

gameover_Subsong0
gameover_Subsong0DisarkGenerateExternalLabel

; Header
gameover_Subsong0DisarkByteRegionStart0
	db 128	; Format version: 0 and endianness: little-endian.
	db 3	; How many channels are encoded.
; Frequency of the PSG index 0: 1000000Hz.
	db 64, 66, 15, 0
gameover_Subsong0DisarkByteRegionEnd0

gameover_Subsong0_Linker
gameover_Subsong0DisarkPointerRegionStart1
; Pattern 0
gameover_Subsong0DisarkWordForceNonReference2
	dw 96	; Duration in frames.
	dw gameover_Subsong0_Track_0
	dw gameover_Subsong0_Track_1
	dw gameover_Subsong0_Track_2

; Pattern 1
gameover_Subsong0DisarkWordForceNonReference3
	dw 96	; Duration in frames.
	dw gameover_Subsong0_Track_8
	dw gameover_Subsong0_Track_4
	dw gameover_Subsong0_Track_5

; Pattern 2
gameover_Subsong0_LinkerLoop	; Loops here.
gameover_Subsong0DisarkWordForceNonReference4
	dw 96	; Duration in frames.
	dw gameover_Subsong0_Track_8
	dw gameover_Subsong0_Track_8
	dw gameover_Subsong0_Track_8

gameover_Subsong0DisarkWordForceNonReference5
	dw 0	; Loops (duration = 0).
	dw gameover_Subsong0_LinkerLoop
gameover_Subsong0DisarkPointerRegionEnd1

; The tracks.
gameover_Subsong0_Track_0
gameover_Subsong0DisarkByteRegionStart6
	db 18	; Duration.
gameover_Subsong0DisarkByteRegionEnd6
gameover_Subsong0DisarkPointerRegionStart7
	dw gameover_Subsong0_RegisterBlock_38
gameover_Subsong0DisarkPointerRegionEnd7

gameover_Subsong0DisarkByteRegionStart8
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd8
gameover_Subsong0DisarkPointerRegionStart9
	dw gameover_Subsong0_RegisterBlock_1
gameover_Subsong0DisarkPointerRegionEnd9

gameover_Subsong0DisarkByteRegionStart10
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd10
gameover_Subsong0DisarkPointerRegionStart11
	dw gameover_Subsong0_RegisterBlock_2
gameover_Subsong0DisarkPointerRegionEnd11

gameover_Subsong0DisarkByteRegionStart12
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd12
gameover_Subsong0DisarkPointerRegionStart13
	dw gameover_Subsong0_RegisterBlock_3
gameover_Subsong0DisarkPointerRegionEnd13

gameover_Subsong0DisarkByteRegionStart14
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd14
gameover_Subsong0DisarkPointerRegionStart15
	dw gameover_Subsong0_RegisterBlock_1
gameover_Subsong0DisarkPointerRegionEnd15

gameover_Subsong0DisarkByteRegionStart16
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd16
gameover_Subsong0DisarkPointerRegionStart17
	dw gameover_Subsong0_RegisterBlock_5
gameover_Subsong0DisarkPointerRegionEnd17

gameover_Subsong0DisarkByteRegionStart18
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd18
gameover_Subsong0DisarkPointerRegionStart19
	dw gameover_Subsong0_RegisterBlock_6
gameover_Subsong0DisarkPointerRegionEnd19

gameover_Subsong0DisarkByteRegionStart20
	db 6	; Duration.
gameover_Subsong0DisarkByteRegionEnd20
gameover_Subsong0DisarkPointerRegionStart21
	dw gameover_Subsong0_RegisterBlock_7
gameover_Subsong0DisarkPointerRegionEnd21

gameover_Subsong0_Track_1
gameover_Subsong0DisarkByteRegionStart22
	db 24	; Duration.
gameover_Subsong0DisarkByteRegionEnd22
gameover_Subsong0DisarkPointerRegionStart23
	dw gameover_Subsong0_RegisterBlock_9
gameover_Subsong0DisarkPointerRegionEnd23

gameover_Subsong0DisarkByteRegionStart24
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd24
gameover_Subsong0DisarkPointerRegionStart25
	dw gameover_Subsong0_RegisterBlock_9
gameover_Subsong0DisarkPointerRegionEnd25

gameover_Subsong0DisarkByteRegionStart26
	db 24	; Duration.
gameover_Subsong0DisarkByteRegionEnd26
gameover_Subsong0DisarkPointerRegionStart27
	dw gameover_Subsong0_RegisterBlock_9
gameover_Subsong0DisarkPointerRegionEnd27

gameover_Subsong0DisarkByteRegionStart28
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd28
gameover_Subsong0DisarkPointerRegionStart29
	dw gameover_Subsong0_RegisterBlock_9
gameover_Subsong0DisarkPointerRegionEnd29

gameover_Subsong0DisarkByteRegionStart30
	db 24	; Duration.
gameover_Subsong0DisarkByteRegionEnd30
gameover_Subsong0DisarkPointerRegionStart31
	dw gameover_Subsong0_RegisterBlock_13
gameover_Subsong0DisarkPointerRegionEnd31

gameover_Subsong0_Track_2
gameover_Subsong0DisarkByteRegionStart32
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd32
gameover_Subsong0DisarkPointerRegionStart33
	dw gameover_Subsong0_RegisterBlock_15
gameover_Subsong0DisarkPointerRegionEnd33

gameover_Subsong0DisarkByteRegionStart34
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd34
gameover_Subsong0DisarkPointerRegionStart35
	dw gameover_Subsong0_RegisterBlock_16
gameover_Subsong0DisarkPointerRegionEnd35

gameover_Subsong0DisarkByteRegionStart36
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd36
gameover_Subsong0DisarkPointerRegionStart37
	dw gameover_Subsong0_RegisterBlock_17
gameover_Subsong0DisarkPointerRegionEnd37

gameover_Subsong0DisarkByteRegionStart38
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd38
gameover_Subsong0DisarkPointerRegionStart39
	dw gameover_Subsong0_RegisterBlock_15
gameover_Subsong0DisarkPointerRegionEnd39

gameover_Subsong0DisarkByteRegionStart40
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd40
gameover_Subsong0DisarkPointerRegionStart41
	dw gameover_Subsong0_RegisterBlock_19
gameover_Subsong0DisarkPointerRegionEnd41

gameover_Subsong0DisarkByteRegionStart42
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd42
gameover_Subsong0DisarkPointerRegionStart43
	dw gameover_Subsong0_RegisterBlock_20
gameover_Subsong0DisarkPointerRegionEnd43

gameover_Subsong0DisarkByteRegionStart44
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd44
gameover_Subsong0DisarkPointerRegionStart45
	dw gameover_Subsong0_RegisterBlock_21
gameover_Subsong0DisarkPointerRegionEnd45

gameover_Subsong0DisarkByteRegionStart46
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd46
gameover_Subsong0DisarkPointerRegionStart47
	dw gameover_Subsong0_RegisterBlock_15
gameover_Subsong0DisarkPointerRegionEnd47

gameover_Subsong0_Track_4
gameover_Subsong0DisarkByteRegionStart48
	db 24	; Duration.
gameover_Subsong0DisarkByteRegionEnd48
gameover_Subsong0DisarkPointerRegionStart49
	dw gameover_Subsong0_RegisterBlock_24
gameover_Subsong0DisarkPointerRegionEnd49

gameover_Subsong0DisarkByteRegionStart50
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd50
gameover_Subsong0DisarkPointerRegionStart51
	dw gameover_Subsong0_RegisterBlock_24
gameover_Subsong0DisarkPointerRegionEnd51

gameover_Subsong0DisarkByteRegionStart52
	db 24	; Duration.
gameover_Subsong0DisarkByteRegionEnd52
gameover_Subsong0DisarkPointerRegionStart53
	dw gameover_Subsong0_RegisterBlock_24
gameover_Subsong0DisarkPointerRegionEnd53

gameover_Subsong0DisarkByteRegionStart54
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd54
gameover_Subsong0DisarkPointerRegionStart55
	dw gameover_Subsong0_RegisterBlock_24
gameover_Subsong0DisarkPointerRegionEnd55

gameover_Subsong0DisarkByteRegionStart56
	db 24	; Duration.
gameover_Subsong0DisarkByteRegionEnd56
gameover_Subsong0DisarkPointerRegionStart57
	dw gameover_Subsong0_RegisterBlock_28
gameover_Subsong0DisarkPointerRegionEnd57

gameover_Subsong0_Track_5
gameover_Subsong0DisarkByteRegionStart58
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd58
gameover_Subsong0DisarkPointerRegionStart59
	dw gameover_Subsong0_RegisterBlock_17
gameover_Subsong0DisarkPointerRegionEnd59

gameover_Subsong0DisarkByteRegionStart60
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd60
gameover_Subsong0DisarkPointerRegionStart61
	dw gameover_Subsong0_RegisterBlock_31
gameover_Subsong0DisarkPointerRegionEnd61

gameover_Subsong0DisarkByteRegionStart62
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd62
gameover_Subsong0DisarkPointerRegionStart63
	dw gameover_Subsong0_RegisterBlock_32
gameover_Subsong0DisarkPointerRegionEnd63

gameover_Subsong0DisarkByteRegionStart64
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd64
gameover_Subsong0DisarkPointerRegionStart65
	dw gameover_Subsong0_RegisterBlock_33
gameover_Subsong0DisarkPointerRegionEnd65

gameover_Subsong0DisarkByteRegionStart66
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd66
gameover_Subsong0DisarkPointerRegionStart67
	dw gameover_Subsong0_RegisterBlock_34
gameover_Subsong0DisarkPointerRegionEnd67

gameover_Subsong0DisarkByteRegionStart68
	db 12	; Duration.
gameover_Subsong0DisarkByteRegionEnd68
gameover_Subsong0DisarkPointerRegionStart69
	dw gameover_Subsong0_RegisterBlock_35
gameover_Subsong0DisarkPointerRegionEnd69

gameover_Subsong0DisarkByteRegionStart70
	db 24	; Duration.
gameover_Subsong0DisarkByteRegionEnd70
gameover_Subsong0DisarkPointerRegionStart71
	dw gameover_Subsong0_RegisterBlock_36
gameover_Subsong0DisarkPointerRegionEnd71

gameover_Subsong0_Track_8
gameover_Subsong0DisarkByteRegionStart72
	db 96	; Duration.
gameover_Subsong0DisarkByteRegionEnd72
gameover_Subsong0DisarkPointerRegionStart73
	dw gameover_Subsong0_RegisterBlock_38
gameover_Subsong0DisarkPointerRegionEnd73


; The RegisterBlocks.
gameover_Subsong0DisarkByteRegionStart74
gameover_Subsong0_RegisterBlock_38
	db 0	; Initial State: no software, no hardware.

gameover_Subsong0_RegisterBlock_38_Loop
	db 4	; Non-initial State, no software no hardware.

	db 8	; Loop to index 1.
gameover_Subsong0DisarkPointerRegionStart75
	dw gameover_Subsong0_RegisterBlock_38_Loop
gameover_Subsong0DisarkPointerRegionEnd75


gameover_Subsong0_RegisterBlock_9
	db 121	; Initial State: software only.
	db 252, 4	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 4	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.


gameover_Subsong0_RegisterBlock_13
	db 121	; Initial State: software only.
	db 126, 2	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.


gameover_Subsong0_RegisterBlock_24
	db 121	; Initial State: software only.
	db 188, 3	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.


gameover_Subsong0_RegisterBlock_28
	db 121	; Initial State: software only.
	db 222, 1	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.


gameover_Subsong0_RegisterBlock_36
	db 113	; Initial State: software only.
	db 238, 14	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.


gameover_Subsong0_RegisterBlock_0
	db 0	; Initial State: no software, no hardware.

	db 8
gameover_Subsong0DisarkPointerRegionStart76
	dw gameover_Subsong0_RegisterBlock_38 + 1	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd76

gameover_Subsong0_RegisterBlock_1
	db 73	; Initial State: software only.
	db 89, 0	; Software period.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 21	; Non-initial State, software only.

	db 21	; Non-initial State, software only.

	db 21	; Non-initial State, software only.


gameover_Subsong0_RegisterBlock_2
	db 73	; Initial State: software only.
	db 80, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart77
	dw gameover_Subsong0_RegisterBlock_1 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd77

gameover_Subsong0_RegisterBlock_3
	db 73	; Initial State: software only.
	db 60, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart78
	dw gameover_Subsong0_RegisterBlock_1 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd78

gameover_Subsong0_RegisterBlock_5
	db 73	; Initial State: software only.
	db 50, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart79
	dw gameover_Subsong0_RegisterBlock_1 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd79

gameover_Subsong0_RegisterBlock_6
	db 73	; Initial State: software only.
	db 53, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart80
	dw gameover_Subsong0_RegisterBlock_1 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd80

gameover_Subsong0_RegisterBlock_15
	db 113	; Initial State: software only.
	db 89, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart81
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd81

gameover_Subsong0_RegisterBlock_16
	db 113	; Initial State: software only.
	db 80, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart82
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd82

gameover_Subsong0_RegisterBlock_17
	db 113	; Initial State: software only.
	db 60, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart83
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd83

gameover_Subsong0_RegisterBlock_19
	db 113	; Initial State: software only.
	db 50, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart84
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd84

gameover_Subsong0_RegisterBlock_20
	db 113	; Initial State: software only.
	db 53, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart85
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd85

gameover_Subsong0_RegisterBlock_21
	db 113	; Initial State: software only.
	db 67, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart86
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd86

gameover_Subsong0_RegisterBlock_31
	db 113	; Initial State: software only.
	db 119, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart87
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd87

gameover_Subsong0_RegisterBlock_32
	db 113	; Initial State: software only.
	db 239, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart88
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd88

gameover_Subsong0_RegisterBlock_33
	db 113	; Initial State: software only.
	db 222, 1	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart89
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd89

gameover_Subsong0_RegisterBlock_34
	db 113	; Initial State: software only.
	db 188, 3	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart90
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd90

gameover_Subsong0_RegisterBlock_35
	db 113	; Initial State: software only.
	db 119, 7	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart91
	dw gameover_Subsong0_RegisterBlock_36 + 3	; Optimization: goto common Block at index 1.
gameover_Subsong0DisarkPointerRegionEnd91

gameover_Subsong0_RegisterBlock_7
	db 73	; Initial State: software only.
	db 67, 0	; Software period.

	db 8
gameover_Subsong0DisarkPointerRegionStart92
	dw gameover_Subsong0_RegisterBlock_36 + 15	; Optimization: goto common Block at index 13.
gameover_Subsong0DisarkPointerRegionEnd92

gameover_Subsong0DisarkByteRegionEnd74
