; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Start
StartDisarkGenerateExternalLabel

DisarkByteRegionStart0
	db "AT20"
DisarkPointerRegionStart1
	dw ArpeggioTable	; The address of the Arpeggio table.
	dw PitchTable	; The address of the Pitch table.
	dw InstrumentTable	; The address of the Instrument table.
	dw EffectBlockTable	; The address of the Effect Block table.
DisarkPointerRegionEnd1


; The addresses of each Subsong:
DisarkPointerRegionStart2
	dw Subsong0_Start
DisarkPointerRegionEnd2

; Declares all the Arpeggios.
ArpeggioTable
DisarkPointerRegionStart3
DisarkPointerRegionEnd3

; Declares all the Pitches.
PitchTable
DisarkPointerRegionStart4
DisarkPointerRegionEnd4

; Declares all the Instruments.
InstrumentTable
DisarkPointerRegionStart5
	dw EmptyInstrument
	dw Instrument1
	dw Instrument2
	dw Instrument3
DisarkPointerRegionEnd5

EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Instrument1
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

Instrument2
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw -10	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw -30	; Pitch.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 80	; No Soft no Hard. Volume: 10. Noise? false.

	db 208	; No Soft no Hard. Volume: 10. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

Instrument3
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
EffectBlockTable
DisarkPointerRegionStart6
	dw EffectBlock_P4P6	; Index 0
DisarkPointerRegionEnd6

EffectBlock_P4P6
	db 4, 6

DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Subsong0_DisarkByteRegionStart0
Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 3	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 0	; Base note index (>=0).

Subsong0_Linker
Subsong0_DisarkPointerRegionStart1
; Position 0
Subsong0_Linker_Loop
	dw Subsong0_Track0
	dw Subsong0_Track1
	dw Subsong0_Track2
	dw Subsong0_LinkerBlock0

; Position 1
	dw Subsong0_Track3
	dw Subsong0_Track4
	dw Subsong0_Track2
	dw Subsong0_LinkerBlock1

; Position 2
	dw Subsong0_Track5
	dw Subsong0_Track6
	dw Subsong0_Track2
	dw Subsong0_LinkerBlock1

; Position 3
	dw Subsong0_Track7
	dw Subsong0_Track8
	dw Subsong0_Track2
	dw Subsong0_LinkerBlock1

Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Subsong0_DisarkWordForceReference2
	dw Subsong0_Linker_Loop

Subsong0_LinkerBlock0
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference3
	dw Subsong0_SpeedTrack0	; SpeedTrack address.
Subsong0_DisarkWordForceReference4
	dw Subsong0_EventTrack0	; EventTrack address.
Subsong0_LinkerBlock1
	db 48	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Subsong0_DisarkWordForceReference5
	dw Subsong0_SpeedTrack1	; SpeedTrack address.
Subsong0_DisarkWordForceReference6
	dw Subsong0_EventTrack0	; EventTrack address.

Subsong0_Track0
	db 235
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 42
	db 40
	db 42
	db 43
	db 60	; Waits for 1 line.

	db 38
	db 42
	db 40
	db 42
	db 43
	db 60	; Waits for 1 line.

	db 38
	db 43
	db 60	; Waits for 1 line.

	db 47
	db 50
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 53
	db 60	; Waits for 1 line.

	db 48
	db 52
	db 50
	db 52
	db 53
	db 60	; Waits for 1 line.

	db 48
	db 52
	db 50
	db 52
	db 53
	db 60	; Waits for 1 line.

	db 53
	db 52
	db 50
	db 48
	db 50
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track1
	db 211
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 19
	db 26
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 26
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 19
	db 60	; Waits for 1 line.

	db 19
	db 26
	db 60	; Waits for 1 line.

	db 26
	db 31
	db 19
	db 19
	db 31
	db 60	; Waits for 1 line.

	db 30
	db 29
	db 60	; Waits for 1 line.

	db 29
	db 24
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 29
	db 60	; Waits for 1 line.

	db 29
	db 36
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 41
	db 60	; Waits for 1 line.

	db 29
	db 36
	db 60	; Waits for 1 line.

	db 24
	db 38
	db 60	; Waits for 1 line.

	db 26
	db 26
	db 61, 127	; Waits for 128 lines.


Subsong0_Track2
	db 240
	db 2	; New Instrument (2).
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 48
	db 48
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 176
	db 2	; New Instrument (2).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 48
	db 48
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 48
	db 48
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 48
	db 60	; Waits for 1 line.

	db 176
	db 3	; New Instrument (3).
	db 176
	db 2	; New Instrument (2).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 48
	db 48
	db 48
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 48
	db 60	; Waits for 1 line.

	db 48
	db 61, 127	; Waits for 128 lines.


Subsong0_Track3
	db 235
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 38
	db 42
	db 40
	db 42
	db 43
	db 60	; Waits for 1 line.

	db 38
	db 42
	db 40
	db 42
	db 43
	db 60	; Waits for 1 line.

	db 38
	db 43
	db 60	; Waits for 1 line.

	db 47
	db 50
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 53
	db 60	; Waits for 1 line.

	db 48
	db 52
	db 50
	db 52
	db 53
	db 60	; Waits for 1 line.

	db 48
	db 52
	db 50
	db 52
	db 53
	db 60	; Waits for 1 line.

	db 53
	db 54
	db 50
	db 54
	db 55
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 47
	db 50
	db 61, 127	; Waits for 128 lines.


Subsong0_Track4
	db 211
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 19
	db 26
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 31
	db 60	; Waits for 1 line.

	db 31
	db 26
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 19
	db 60	; Waits for 1 line.

	db 19
	db 26
	db 60	; Waits for 1 line.

	db 26
	db 31
	db 19
	db 19
	db 31
	db 60	; Waits for 1 line.

	db 30
	db 29
	db 60	; Waits for 1 line.

	db 29
	db 24
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 29
	db 60	; Waits for 1 line.

	db 29
	db 36
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 41
	db 60	; Waits for 1 line.

	db 29
	db 38
	db 60	; Waits for 1 line.

	db 26
	db 31
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 19
	db 61, 127	; Waits for 128 lines.


Subsong0_Track5
	db 180
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 51
	db 52
	db 60	; Waits for 1 line.

	db 51
	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 54
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 45
	db 47
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 48
	db 60	; Waits for 1 line.

	db 47
	db 48
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 60	; Waits for 1 line.

	db 48
	db 47
	db 60	; Waits for 1 line.

	db 46
	db 47
	db 60	; Waits for 1 line.

	db 48
	db 50
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 43
	db 61, 127	; Waits for 128 lines.


Subsong0_Track6
	db 164
	db 1	; New Instrument (1).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 24
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 60	; Waits for 1 line.

	db 24
	db 26
	db 60	; Waits for 1 line.

	db 24
	db 23
	db 60	; Waits for 1 line.

	db 22
	db 23
	db 60	; Waits for 1 line.

	db 26
	db 31
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 23
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 60	; Waits for 1 line.

	db 24
	db 24
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 38
	db 60	; Waits for 1 line.

	db 26
	db 38
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 31
	db 60	; Waits for 1 line.

	db 18
	db 19
	db 60	; Waits for 1 line.

	db 21
	db 23
	db 60	; Waits for 1 line.

	db 26
	db 31
	db 61, 127	; Waits for 128 lines.


Subsong0_Track7
	db 179
	db 1	; New Instrument (1).
	db 60	; Waits for 1 line.

	db 50
	db 51
	db 60	; Waits for 1 line.

	db 55
	db 53
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 51
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 60	; Waits for 1 line.

	db 49
	db 50
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 48
	db 60	; Waits for 1 line.

	db 46
	db 45
	db 60	; Waits for 1 line.

	db 44
	db 45
	db 60	; Waits for 1 line.

	db 49
	db 52
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 54
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 50
	db 61, 9	; Waits for 10 lines.

	db 38
	db 61, 127	; Waits for 128 lines.


Subsong0_Track8
	db 152
	db 1	; New Instrument (1).
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 36
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 29
	db 60	; Waits for 1 line.

	db 17
	db 17
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 22
	db 60	; Waits for 1 line.

	db 21
	db 22
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 27
	db 60	; Waits for 1 line.

	db 15
	db 27
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 33
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 21
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 33
	db 60	; Waits for 1 line.

	db 21
	db 33
	db 60	; Waits for 1 line.

	db 21
	db 26
	db 60	; Waits for 1 line.

	db 26
	db 28
	db 60	; Waits for 1 line.

	db 29
	db 30
	db 60	; Waits for 1 line.

	db 26
	db 38
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Subsong0_SpeedTrack0
	db 12	; Value: 6.
	db 253	; Wait for 127 lines.
Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Subsong0_DisarkByteRegionEnd0
