; Song Untitled, in AKY version 1.0, generated by Arkos Tracker 2.

start_Subsong0
start_Subsong0DisarkGenerateExternalLabel

; Header
start_Subsong0DisarkByteRegionStart0
	db 128	; Format version: 0 and endianness: little-endian.
	db 3	; How many channels are encoded.
; Frequency of the PSG index 0: 1000000Hz.
	db 64, 66, 15, 0
start_Subsong0DisarkByteRegionEnd0

start_Subsong0_Linker
start_Subsong0DisarkPointerRegionStart1
; Pattern 0
start_Subsong0DisarkWordForceNonReference2
	dw 192	; Duration in frames.
	dw start_Subsong0_Track_0
	dw start_Subsong0_Track_1
	dw start_Subsong0_Track_2

; Pattern 1
start_Subsong0_LinkerLoop	; Loops here.
start_Subsong0DisarkWordForceNonReference3
	dw 192	; Duration in frames.
	dw start_Subsong0_Track_5
	dw start_Subsong0_Track_5
	dw start_Subsong0_Track_5

start_Subsong0DisarkWordForceNonReference4
	dw 0	; Loops (duration = 0).
	dw start_Subsong0_LinkerLoop
start_Subsong0DisarkPointerRegionEnd1

; The tracks.
start_Subsong0_Track_0
start_Subsong0DisarkByteRegionStart5
	db 36	; Duration.
start_Subsong0DisarkByteRegionEnd5
start_Subsong0DisarkPointerRegionStart6
	dw start_Subsong0_RegisterBlock_5
start_Subsong0DisarkPointerRegionEnd6

start_Subsong0DisarkByteRegionStart7
	db 36	; Duration.
start_Subsong0DisarkByteRegionEnd7
start_Subsong0DisarkPointerRegionStart8
	dw start_Subsong0_RegisterBlock_1
start_Subsong0DisarkPointerRegionEnd8

start_Subsong0DisarkByteRegionStart9
	db 24	; Duration.
start_Subsong0DisarkByteRegionEnd9
start_Subsong0DisarkPointerRegionStart10
	dw start_Subsong0_RegisterBlock_2
start_Subsong0DisarkPointerRegionEnd10

start_Subsong0DisarkByteRegionStart11
	db 12	; Duration.
start_Subsong0DisarkByteRegionEnd11
start_Subsong0DisarkPointerRegionStart12
	dw start_Subsong0_RegisterBlock_5
start_Subsong0DisarkPointerRegionEnd12

start_Subsong0DisarkByteRegionStart13
	db 24	; Duration.
start_Subsong0DisarkByteRegionEnd13
start_Subsong0DisarkPointerRegionStart14
	dw start_Subsong0_RegisterBlock_5
start_Subsong0DisarkPointerRegionEnd14

start_Subsong0DisarkByteRegionStart15
	db 60	; Duration.
start_Subsong0DisarkByteRegionEnd15
start_Subsong0DisarkPointerRegionStart16
	dw start_Subsong0_RegisterBlock_5
start_Subsong0DisarkPointerRegionEnd16

start_Subsong0_Track_1
start_Subsong0DisarkByteRegionStart17
	db 24	; Duration.
start_Subsong0DisarkByteRegionEnd17
start_Subsong0DisarkPointerRegionStart18
	dw start_Subsong0_RegisterBlock_7
start_Subsong0DisarkPointerRegionEnd18

start_Subsong0DisarkByteRegionStart19
	db 12	; Duration.
start_Subsong0DisarkByteRegionEnd19
start_Subsong0DisarkPointerRegionStart20
	dw start_Subsong0_RegisterBlock_7
start_Subsong0DisarkPointerRegionEnd20

start_Subsong0DisarkByteRegionStart21
	db 24	; Duration.
start_Subsong0DisarkByteRegionEnd21
start_Subsong0DisarkPointerRegionStart22
	dw start_Subsong0_RegisterBlock_9
start_Subsong0DisarkPointerRegionEnd22

start_Subsong0DisarkByteRegionStart23
	db 24	; Duration.
start_Subsong0DisarkByteRegionEnd23
start_Subsong0DisarkPointerRegionStart24
	dw start_Subsong0_RegisterBlock_7
start_Subsong0DisarkPointerRegionEnd24

start_Subsong0DisarkByteRegionStart25
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd25
start_Subsong0DisarkPointerRegionStart26
	dw start_Subsong0_RegisterBlock_7
start_Subsong0DisarkPointerRegionEnd26

start_Subsong0DisarkByteRegionStart27
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd27
start_Subsong0DisarkPointerRegionStart28
	dw start_Subsong0_RegisterBlock_9
start_Subsong0DisarkPointerRegionEnd28

start_Subsong0DisarkByteRegionStart29
	db 12	; Duration.
start_Subsong0DisarkByteRegionEnd29
start_Subsong0DisarkPointerRegionStart30
	dw start_Subsong0_RegisterBlock_17
start_Subsong0DisarkPointerRegionEnd30

start_Subsong0DisarkByteRegionStart31
	db 12	; Duration.
start_Subsong0DisarkByteRegionEnd31
start_Subsong0DisarkPointerRegionStart32
	dw start_Subsong0_RegisterBlock_7
start_Subsong0DisarkPointerRegionEnd32

start_Subsong0DisarkByteRegionStart33
	db 12	; Duration.
start_Subsong0DisarkByteRegionEnd33
start_Subsong0DisarkPointerRegionStart34
	dw start_Subsong0_RegisterBlock_7
start_Subsong0DisarkPointerRegionEnd34

start_Subsong0DisarkByteRegionStart35
	db 12	; Duration.
start_Subsong0DisarkByteRegionEnd35
start_Subsong0DisarkPointerRegionStart36
	dw start_Subsong0_RegisterBlock_9
start_Subsong0DisarkPointerRegionEnd36

start_Subsong0DisarkByteRegionStart37
	db 48	; Duration.
start_Subsong0DisarkByteRegionEnd37
start_Subsong0DisarkPointerRegionStart38
	dw start_Subsong0_RegisterBlock_17
start_Subsong0DisarkPointerRegionEnd38

start_Subsong0_Track_2
start_Subsong0DisarkByteRegionStart39
	db 12	; Duration.
start_Subsong0DisarkByteRegionEnd39
start_Subsong0DisarkPointerRegionStart40
	dw start_Subsong0_RegisterBlock_19
start_Subsong0DisarkPointerRegionEnd40

start_Subsong0DisarkByteRegionStart41
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd41
start_Subsong0DisarkPointerRegionStart42
	dw start_Subsong0_RegisterBlock_20
start_Subsong0DisarkPointerRegionEnd42

start_Subsong0DisarkByteRegionStart43
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd43
start_Subsong0DisarkPointerRegionStart44
	dw start_Subsong0_RegisterBlock_21
start_Subsong0DisarkPointerRegionEnd44

start_Subsong0DisarkByteRegionStart45
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd45
start_Subsong0DisarkPointerRegionStart46
	dw start_Subsong0_RegisterBlock_22
start_Subsong0DisarkPointerRegionEnd46

start_Subsong0DisarkByteRegionStart47
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd47
start_Subsong0DisarkPointerRegionStart48
	dw start_Subsong0_RegisterBlock_23
start_Subsong0DisarkPointerRegionEnd48

start_Subsong0DisarkByteRegionStart49
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd49
start_Subsong0DisarkPointerRegionStart50
	dw start_Subsong0_RegisterBlock_42
start_Subsong0DisarkPointerRegionEnd50

start_Subsong0DisarkByteRegionStart51
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd51
start_Subsong0DisarkPointerRegionStart52
	dw start_Subsong0_RegisterBlock_25
start_Subsong0DisarkPointerRegionEnd52

start_Subsong0DisarkByteRegionStart53
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd53
start_Subsong0DisarkPointerRegionStart54
	dw start_Subsong0_RegisterBlock_26
start_Subsong0DisarkPointerRegionEnd54

start_Subsong0DisarkByteRegionStart55
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd55
start_Subsong0DisarkPointerRegionStart56
	dw start_Subsong0_RegisterBlock_27
start_Subsong0DisarkPointerRegionEnd56

start_Subsong0DisarkByteRegionStart57
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd57
start_Subsong0DisarkPointerRegionStart58
	dw start_Subsong0_RegisterBlock_42
start_Subsong0DisarkPointerRegionEnd58

start_Subsong0DisarkByteRegionStart59
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd59
start_Subsong0DisarkPointerRegionStart60
	dw start_Subsong0_RegisterBlock_29
start_Subsong0DisarkPointerRegionEnd60

start_Subsong0DisarkByteRegionStart61
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd61
start_Subsong0DisarkPointerRegionStart62
	dw start_Subsong0_RegisterBlock_22
start_Subsong0DisarkPointerRegionEnd62

start_Subsong0DisarkByteRegionStart63
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd63
start_Subsong0DisarkPointerRegionStart64
	dw start_Subsong0_RegisterBlock_27
start_Subsong0DisarkPointerRegionEnd64

start_Subsong0DisarkByteRegionStart65
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd65
start_Subsong0DisarkPointerRegionStart66
	dw start_Subsong0_RegisterBlock_42
start_Subsong0DisarkPointerRegionEnd66

start_Subsong0DisarkByteRegionStart67
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd67
start_Subsong0DisarkPointerRegionStart68
	dw start_Subsong0_RegisterBlock_25
start_Subsong0DisarkPointerRegionEnd68

start_Subsong0DisarkByteRegionStart69
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd69
start_Subsong0DisarkPointerRegionStart70
	dw start_Subsong0_RegisterBlock_26
start_Subsong0DisarkPointerRegionEnd70

start_Subsong0DisarkByteRegionStart71
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd71
start_Subsong0DisarkPointerRegionStart72
	dw start_Subsong0_RegisterBlock_27
start_Subsong0DisarkPointerRegionEnd72

start_Subsong0DisarkByteRegionStart73
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd73
start_Subsong0DisarkPointerRegionStart74
	dw start_Subsong0_RegisterBlock_42
start_Subsong0DisarkPointerRegionEnd74

start_Subsong0DisarkByteRegionStart75
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd75
start_Subsong0DisarkPointerRegionStart76
	dw start_Subsong0_RegisterBlock_29
start_Subsong0DisarkPointerRegionEnd76

start_Subsong0DisarkByteRegionStart77
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd77
start_Subsong0DisarkPointerRegionStart78
	dw start_Subsong0_RegisterBlock_38
start_Subsong0DisarkPointerRegionEnd78

start_Subsong0DisarkByteRegionStart79
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd79
start_Subsong0DisarkPointerRegionStart80
	dw start_Subsong0_RegisterBlock_27
start_Subsong0DisarkPointerRegionEnd80

start_Subsong0DisarkByteRegionStart81
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd81
start_Subsong0DisarkPointerRegionStart82
	dw start_Subsong0_RegisterBlock_40
start_Subsong0DisarkPointerRegionEnd82

start_Subsong0DisarkByteRegionStart83
	db 6	; Duration.
start_Subsong0DisarkByteRegionEnd83
start_Subsong0DisarkPointerRegionStart84
	dw start_Subsong0_RegisterBlock_41
start_Subsong0DisarkPointerRegionEnd84

start_Subsong0DisarkByteRegionStart85
	db 48	; Duration.
start_Subsong0DisarkByteRegionEnd85
start_Subsong0DisarkPointerRegionStart86
	dw start_Subsong0_RegisterBlock_42
start_Subsong0DisarkPointerRegionEnd86

start_Subsong0_Track_5
start_Subsong0DisarkByteRegionStart87
	db 192	; Duration.
start_Subsong0DisarkByteRegionEnd87
start_Subsong0DisarkPointerRegionStart88
	dw start_Subsong0_RegisterBlock_44
start_Subsong0DisarkPointerRegionEnd88


; The RegisterBlocks.
start_Subsong0DisarkByteRegionStart89
start_Subsong0_RegisterBlock_44
	db 0	; Initial State: no software, no hardware.

start_Subsong0_RegisterBlock_44_Loop
	db 4	; Non-initial State, no software no hardware.

	db 8	; Loop to index 1.
start_Subsong0DisarkPointerRegionStart90
	dw start_Subsong0_RegisterBlock_44_Loop
start_Subsong0DisarkPointerRegionEnd90


start_Subsong0_RegisterBlock_5
	db 121	; Initial State: software only.
	db 188, 3	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

start_Subsong0_RegisterBlock_5_Loop
	db 225	; Non-initial State, software only.
	db 188	; New LSB for software period.
	db 3	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
start_Subsong0DisarkPointerRegionStart91
	dw start_Subsong0_RegisterBlock_5_Loop
start_Subsong0DisarkPointerRegionEnd91


start_Subsong0_RegisterBlock_17
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 30, 0	; Software period.

	db 241	; Non-initial State, software only.
	db 14	; New LSB for software period.
	db 128	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 255	; New MSB for software period, maybe with noise.
	db 15	; New noise.

	db 8
start_Subsong0DisarkPointerRegionStart92
	dw start_Subsong0_RegisterBlock_44 + 1	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd92

start_Subsong0_RegisterBlock_42
	db 113	; Initial State: software only.
	db 119, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 8
start_Subsong0DisarkPointerRegionStart93
	dw start_Subsong0_RegisterBlock_44 + 1	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd93

start_Subsong0_RegisterBlock_0
	db 121	; Initial State: software only.
	db 188, 3	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart94
	dw start_Subsong0_RegisterBlock_5 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd94

start_Subsong0_RegisterBlock_1
	db 121	; Initial State: software only.
	db 204, 2	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

start_Subsong0_RegisterBlock_1_Loop
	db 225	; Non-initial State, software only.
	db 204	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
start_Subsong0DisarkPointerRegionStart95
	dw start_Subsong0_RegisterBlock_1_Loop
start_Subsong0DisarkPointerRegionEnd95


start_Subsong0_RegisterBlock_2
	db 121	; Initial State: software only.
	db 126, 2	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 126	; New LSB for software period.
	db 2	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.


start_Subsong0_RegisterBlock_7
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 119, 0	; Software period.

	db 241	; Non-initial State, software only.
	db 103	; New LSB for software period.
	db 128	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 55	; New LSB for software period.
	db 192	; New MSB for software period, maybe with noise.
	db 15	; New noise.

	db 8
start_Subsong0DisarkPointerRegionStart96
	dw start_Subsong0_RegisterBlock_44 + 1	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd96

start_Subsong0_RegisterBlock_9
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 60, 0	; Software period.

	db 241	; Non-initial State, software only.
	db 44	; New LSB for software period.
	db 128	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 252	; New LSB for software period.
	db 255	; New MSB for software period, maybe with noise.
	db 15	; New noise.

	db 8
start_Subsong0DisarkPointerRegionStart97
	dw start_Subsong0_RegisterBlock_44 + 1	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd97

start_Subsong0_RegisterBlock_13
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 30, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart98
	dw start_Subsong0_RegisterBlock_17 + 4	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd98

start_Subsong0_RegisterBlock_19
	db 113	; Initial State: software only.
	db 239, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart99
	dw start_Subsong0_RegisterBlock_42 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd99

start_Subsong0_RegisterBlock_20
	db 113	; Initial State: software only.
	db 213, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart100
	dw start_Subsong0_RegisterBlock_42 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd100

start_Subsong0_RegisterBlock_21
	db 89	; Initial State: software only.
	db 239, 0	; Software period.

	db 45	; Non-initial State, software only.

	db 45	; Non-initial State, software only.

	db 8
start_Subsong0DisarkPointerRegionStart101
	dw start_Subsong0_RegisterBlock_42 + 11	; Optimization: goto common Block at index 9.
start_Subsong0DisarkPointerRegionEnd101

start_Subsong0_RegisterBlock_22
	db 113	; Initial State: software only.
	db 159, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart102
	dw start_Subsong0_RegisterBlock_42 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd102

start_Subsong0_RegisterBlock_23
	db 89	; Initial State: software only.
	db 213, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart103
	dw start_Subsong0_RegisterBlock_21 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd103

start_Subsong0_RegisterBlock_24
	db 113	; Initial State: software only.
	db 119, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart104
	dw start_Subsong0_RegisterBlock_42 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd104

start_Subsong0_RegisterBlock_25
	db 89	; Initial State: software only.
	db 159, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart105
	dw start_Subsong0_RegisterBlock_21 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd105

start_Subsong0_RegisterBlock_26
	db 113	; Initial State: software only.
	db 106, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart106
	dw start_Subsong0_RegisterBlock_42 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd106

start_Subsong0_RegisterBlock_27
	db 89	; Initial State: software only.
	db 119, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart107
	dw start_Subsong0_RegisterBlock_21 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd107

start_Subsong0_RegisterBlock_29
	db 89	; Initial State: software only.
	db 106, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart108
	dw start_Subsong0_RegisterBlock_21 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd108

start_Subsong0_RegisterBlock_38
	db 113	; Initial State: software only.
	db 80, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart109
	dw start_Subsong0_RegisterBlock_42 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd109

start_Subsong0_RegisterBlock_40
	db 113	; Initial State: software only.
	db 60, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart110
	dw start_Subsong0_RegisterBlock_42 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd110

start_Subsong0_RegisterBlock_41
	db 89	; Initial State: software only.
	db 80, 0	; Software period.

	db 8
start_Subsong0DisarkPointerRegionStart111
	dw start_Subsong0_RegisterBlock_21 + 3	; Optimization: goto common Block at index 1.
start_Subsong0DisarkPointerRegionEnd111

start_Subsong0DisarkByteRegionEnd89
