; Song A Harmless Grenade in Lightweight format (V1).
; Generated by Arkos Tracker 2.

AHarmlessGrenade_Start
AHarmlessGrenade_StartDisarkGenerateExternalLabel

AHarmlessGrenade_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
AHarmlessGrenade_DisarkByteRegionEnd0
AHarmlessGrenade_DisarkPointerRegionStart1
	dw AHarmlessGrenade_FmInstrumentTable
	dw AHarmlessGrenade_ArpeggioTable
	dw AHarmlessGrenade_PitchTable
; Table of the Subsongs.
	dw AHarmlessGrenade_Subsong0
AHarmlessGrenade_DisarkPointerRegionEnd1

; The Arpeggio table.
AHarmlessGrenade_ArpeggioTable
AHarmlessGrenade_DisarkWordRegionStart2
	dw 0
AHarmlessGrenade_DisarkWordRegionEnd2
AHarmlessGrenade_DisarkPointerRegionStart3
	dw AHarmlessGrenade_Arpeggio1
	dw AHarmlessGrenade_Arpeggio2
AHarmlessGrenade_DisarkPointerRegionEnd3

; The Pitch table.
AHarmlessGrenade_PitchTable
AHarmlessGrenade_DisarkWordRegionStart4
	dw 0
AHarmlessGrenade_DisarkWordRegionEnd4
AHarmlessGrenade_DisarkPointerRegionStart5
	dw AHarmlessGrenade_Pitch1
AHarmlessGrenade_DisarkPointerRegionEnd5

; The FM Instrument table.
AHarmlessGrenade_FmInstrumentTable
AHarmlessGrenade_DisarkPointerRegionStart6
	dw AHarmlessGrenade_FmInstrument0
	dw AHarmlessGrenade_FmInstrument1
	dw AHarmlessGrenade_FmInstrument2
	dw AHarmlessGrenade_FmInstrument3
	dw AHarmlessGrenade_FmInstrument4
	dw AHarmlessGrenade_FmInstrument5
	dw AHarmlessGrenade_FmInstrument6
	dw AHarmlessGrenade_FmInstrument7
	dw AHarmlessGrenade_FmInstrument8
	dw AHarmlessGrenade_FmInstrument9
	dw AHarmlessGrenade_FmInstrument10
	dw AHarmlessGrenade_FmInstrument11
	dw AHarmlessGrenade_FmInstrument12
	dw AHarmlessGrenade_FmInstrument13
	dw AHarmlessGrenade_FmInstrument14
	dw AHarmlessGrenade_FmInstrument15
	dw AHarmlessGrenade_FmInstrument16
	dw AHarmlessGrenade_FmInstrument17
	dw AHarmlessGrenade_FmInstrument18
	dw AHarmlessGrenade_FmInstrument19
AHarmlessGrenade_DisarkPointerRegionEnd6

AHarmlessGrenade_Arpeggio1
AHarmlessGrenade_DisarkByteRegionStart7
	db 0	; Value: 0
	db 24	; Value: 12
	db 18	; Value: 9
	db -24	; Value: -12
	db 36	; Value: 18
	db 1	; End, loop to index 0
AHarmlessGrenade_DisarkByteRegionEnd7

AHarmlessGrenade_Arpeggio2
AHarmlessGrenade_DisarkByteRegionStart8
	db 0	; Value: 0
	db 12	; Value: 6
	db -6	; Value: -3
	db -24	; Value: -12
	db -12	; Value: -6
	db 0	; Value: 0
	db 24	; Value: 12
	db 1	; End, loop to index 0
AHarmlessGrenade_DisarkByteRegionEnd8

AHarmlessGrenade_Pitch1
AHarmlessGrenade_DisarkByteRegionStart9
	db 0	; Value: 0
	db 0	; Value: 0
	db 0	; Value: 0
	db 0	; Value: 0
	db 0	; Value: 0
	db 0	; Value: 0
	db -2	; Value: -1
	db -2	; Value: -1
	db -8	; Value: -4
	db -8	; Value: -4
	db 4	; Value: 2
	db 4	; Value: 2
	db 9	; End, loop to index 4
AHarmlessGrenade_DisarkByteRegionEnd9

AHarmlessGrenade_DisarkByteRegionStart10
AHarmlessGrenade_FmInstrument0
	db 255	; Speed.

AHarmlessGrenade_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart11
	dw AHarmlessGrenade_FmInstrument0Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd11

AHarmlessGrenade_FmInstrument1
	db 1	; Speed.

	db 162, 12	; Arpeggio: 12.

	db 194, 12	; Arpeggio: 12.

	db 194, 12	; Arpeggio: 12.

	db 34
	db 169	; Volume: 10.
	db 24	; Arpeggio: 12.

	db 41	; Volume: 10.

	db 169	; Volume: 10.
	db 24	; Arpeggio: 12.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart12
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd12

AHarmlessGrenade_FmInstrument2
	db 0	; Speed.

	db 189	; Volume: 15.
	db 1	; Arpeggio: 0.
	db 2	; Noise: 2.

	db 253	; Volume: 15.
	db 1	; Arpeggio: 0.
	db 1	; Noise: 1.
	dw 32	; Pitch: 32.

	db 125	; Volume: 15.
	dw 48	; Pitch: 48.

	db 125	; Volume: 15.
	dw 68	; Pitch: 68.

	db 125	; Volume: 15.
	dw 116	; Pitch: 116.

	db 125	; Volume: 15.
	dw 228	; Pitch: 228.

	db 121	; Volume: 14.
	dw 180	; Pitch: 180.

	db 117	; Volume: 13.
	dw 292	; Pitch: 292.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart13
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd13

AHarmlessGrenade_FmInstrument3
	db 0	; Speed.

	db 248	; Volume: 15.
	db 1	; Noise.

	db 216	; Volume: 11.
	db 1	; Noise.

	db 184	; Volume: 7.
	db 1	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart14
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd14

AHarmlessGrenade_FmInstrument4
	db 0	; Speed.

	db 248	; Volume: 15.
	db 4	; Noise.

	db 200	; Volume: 9.
	db 1	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart15
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd15

AHarmlessGrenade_FmInstrument5
	db 0	; Speed.

AHarmlessGrenade_FmInstrument5Loop	db 248	; Volume: 15.
	db 1	; Noise.

	db 200	; Volume: 9.
	db 1	; Noise.

	db 176	; Volume: 6.
	db 1	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart16
	dw AHarmlessGrenade_FmInstrument5Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd16

AHarmlessGrenade_FmInstrument6
	db 3	; Speed.

	db 248	; Volume: 15.
	db 1	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart17
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd17

AHarmlessGrenade_FmInstrument7
	db 2	; Speed.

	db 61	; Volume: 15.

	db 53	; Volume: 13.

	db 49	; Volume: 12.

	db 45	; Volume: 11.

	db 41	; Volume: 10.

	db 37	; Volume: 9.

	db 33	; Volume: 8.

	db 29	; Volume: 7.

	db 25	; Volume: 6.

	db 21	; Volume: 5.

	db 17	; Volume: 4.

	db 13	; Volume: 3.

	db 9	; Volume: 2.

	db 5	; Volume: 1.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart18
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd18

AHarmlessGrenade_FmInstrument8
	db 0	; Speed.

AHarmlessGrenade_FmInstrument8Loop	db 58
	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart19
	dw AHarmlessGrenade_FmInstrument8Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd19

AHarmlessGrenade_FmInstrument9
	db 0	; Speed.

	db 248	; Volume: 15.
	db 2	; Noise.

	db 57	; Volume: 14.

	db 245	; Volume: 13.
	db 1	; Arpeggio: 0.
	db 1	; Noise: 1.
	dw 208	; Pitch: 208.

	db 237	; Volume: 11.
	db 1	; Arpeggio: 0.
	db 1	; Noise: 1.
	dw 400	; Pitch: 400.

	db 216	; Volume: 11.
	db 1	; Noise.

	db 216	; Volume: 11.
	db 3	; Noise.

	db 208	; Volume: 10.
	db 4	; Noise.

	db 200	; Volume: 9.
	db 1	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart20
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd20

AHarmlessGrenade_FmInstrument10
	db 4	; Speed.

AHarmlessGrenade_FmInstrument10Loop	db 34
	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart21
	dw AHarmlessGrenade_FmInstrument10Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd21

AHarmlessGrenade_FmInstrument11
	db 1	; Speed.

AHarmlessGrenade_FmInstrument11Loop	db 178, 12	; Arpeggio: 12.

	db 178, 12	; Arpeggio: 12.

	db 120	; Volume: 15.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart22
	dw AHarmlessGrenade_FmInstrument11Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd22

AHarmlessGrenade_FmInstrument12
	db 0	; Speed.

AHarmlessGrenade_FmInstrument12Loop	db 61	; Volume: 15.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart23
	dw AHarmlessGrenade_FmInstrument12Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd23

AHarmlessGrenade_FmInstrument13
	db 0	; Speed.

	db 61	; Volume: 15.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart24
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd24

AHarmlessGrenade_FmInstrument14
	db 0	; Speed.

AHarmlessGrenade_FmInstrument14Loop	db 74
	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart25
	dw AHarmlessGrenade_FmInstrument14Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd25

AHarmlessGrenade_FmInstrument15
	db 1	; Speed.

	db 61	; Volume: 15.

AHarmlessGrenade_FmInstrument15Loop	db 121	; Volume: 14.
	dw -5	; Pitch: -5.

	db 49	; Volume: 12.

	db 109	; Volume: 11.
	dw 5	; Pitch: 5.

	db 61	; Volume: 15.

	db 117	; Volume: 13.
	dw -7	; Pitch: -7.

	db 37	; Volume: 9.

	db 105	; Volume: 10.
	dw 32	; Pitch: 32.

	db 45	; Volume: 11.

	db 49	; Volume: 12.

	db 57	; Volume: 14.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart26
	dw AHarmlessGrenade_FmInstrument15Loop	; Loops.
AHarmlessGrenade_DisarkPointerRegionEnd26

AHarmlessGrenade_FmInstrument16
	db 0	; Speed.

	db 232	; Volume: 13.
	db 5	; Noise.

	db 216	; Volume: 11.
	db 5	; Noise.

	db 208	; Volume: 10.
	db 5	; Noise.

	db 200	; Volume: 9.
	db 5	; Noise.

	db 184	; Volume: 7.
	db 5	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart27
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd27

AHarmlessGrenade_FmInstrument17
	db 0	; Speed.

	db 232	; Volume: 13.
	db 9	; Noise.

	db 216	; Volume: 11.
	db 9	; Noise.

	db 208	; Volume: 10.
	db 9	; Noise.

	db 200	; Volume: 9.
	db 9	; Noise.

	db 184	; Volume: 7.
	db 9	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart28
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd28

AHarmlessGrenade_FmInstrument18
	db 0	; Speed.

	db 232	; Volume: 13.
	db 17	; Noise.

	db 216	; Volume: 11.
	db 17	; Noise.

	db 208	; Volume: 10.
	db 17	; Noise.

	db 200	; Volume: 9.
	db 17	; Noise.

	db 184	; Volume: 7.
	db 17	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart29
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd29

AHarmlessGrenade_FmInstrument19
	db 0	; Speed.

	db 232	; Volume: 13.
	db 25	; Noise.

	db 216	; Volume: 11.
	db 25	; Noise.

	db 208	; Volume: 10.
	db 25	; Noise.

	db 200	; Volume: 9.
	db 25	; Noise.

	db 184	; Volume: 7.
	db 25	; Noise.

	db 4	; End the instrument.
AHarmlessGrenade_DisarkPointerRegionStart30
	dw AHarmlessGrenade_FmInstrument0Loop	; Loop to silence.
AHarmlessGrenade_DisarkPointerRegionEnd30

AHarmlessGrenade_DisarkByteRegionEnd10
AHarmlessGrenade_Subsong0DisarkByteRegionStart0
; Song A Harmless Grenade, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

AHarmlessGrenade_Subsong0
	db 6	; Initial speed.

; The Linker.
; Pattern 0
AHarmlessGrenade_Subsong0loop
	db 13	; State byte.
	db 31	; New height.
	db 0, 0, 0	; The transpositions.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart1
	dw AHarmlessGrenade_Subsong0_Track0, AHarmlessGrenade_Subsong0_Track22, AHarmlessGrenade_Subsong0_Track22
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart2
	dw AHarmlessGrenade_Subsong0_Track0, AHarmlessGrenade_Subsong0_Track1, AHarmlessGrenade_Subsong0_Track1
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart3
	dw AHarmlessGrenade_Subsong0_Track0, AHarmlessGrenade_Subsong0_Track1, AHarmlessGrenade_Subsong0_Track2
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart4
	dw AHarmlessGrenade_Subsong0_Track0, AHarmlessGrenade_Subsong0_Track1, AHarmlessGrenade_Subsong0_Track2
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart5
	dw AHarmlessGrenade_Subsong0_Track3, AHarmlessGrenade_Subsong0_Track5, AHarmlessGrenade_Subsong0_Track4
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 5	; State byte.
	db 23	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart6
	dw AHarmlessGrenade_Subsong0_Track6, AHarmlessGrenade_Subsong0_Track8, AHarmlessGrenade_Subsong0_Track7
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd6
; The tracks.

; Pattern 6
	db 5	; State byte.
	db 7	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart7
	dw AHarmlessGrenade_Subsong0_Track9, AHarmlessGrenade_Subsong0_Track10, AHarmlessGrenade_Subsong0_Track11
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd7
; The tracks.

; Pattern 7
	db 5	; State byte.
	db 23	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart8
	dw AHarmlessGrenade_Subsong0_Track6, AHarmlessGrenade_Subsong0_Track8, AHarmlessGrenade_Subsong0_Track7
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd8
; The tracks.

; Pattern 8
	db 5	; State byte.
	db 7	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart9
	dw AHarmlessGrenade_Subsong0_Track12, AHarmlessGrenade_Subsong0_Track13, AHarmlessGrenade_Subsong0_Track14
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd9
; The tracks.

; Pattern 9
	db 5	; State byte.
	db 23	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart10
	dw AHarmlessGrenade_Subsong0_Track6, AHarmlessGrenade_Subsong0_Track8, AHarmlessGrenade_Subsong0_Track7
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd10
; The tracks.

; Pattern 10
	db 5	; State byte.
	db 7	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart11
	dw AHarmlessGrenade_Subsong0_Track9, AHarmlessGrenade_Subsong0_Track10, AHarmlessGrenade_Subsong0_Track11
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd11
; The tracks.

; Pattern 11
	db 5	; State byte.
	db 31	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart12
	dw AHarmlessGrenade_Subsong0_Track15, AHarmlessGrenade_Subsong0_Track16, AHarmlessGrenade_Subsong0_Track17
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd12
; The tracks.

; Pattern 12
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart13
	dw AHarmlessGrenade_Subsong0_Track15, AHarmlessGrenade_Subsong0_Track16, AHarmlessGrenade_Subsong0_Track20
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd13
; The tracks.

; Pattern 13
	db 5	; State byte.
	db 27	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart14
	dw AHarmlessGrenade_Subsong0_Track15, AHarmlessGrenade_Subsong0_Track16, AHarmlessGrenade_Subsong0_Track17
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd14
; The tracks.

; Pattern 14
	db 5	; State byte.
	db 3	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart15
	dw AHarmlessGrenade_Subsong0_Track22, AHarmlessGrenade_Subsong0_Track23, AHarmlessGrenade_Subsong0_Track22
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd15
; The tracks.

; Pattern 15
	db 5	; State byte.
	db 31	; New height.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart16
	dw AHarmlessGrenade_Subsong0_Track18, AHarmlessGrenade_Subsong0_Track19, AHarmlessGrenade_Subsong0_Track21
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd16
; The tracks.

; Pattern 16
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart17
	dw AHarmlessGrenade_Subsong0_Track18, AHarmlessGrenade_Subsong0_Track19, AHarmlessGrenade_Subsong0_Track21
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd17
; The tracks.

; Pattern 17
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart18
	dw AHarmlessGrenade_Subsong0_Track24, AHarmlessGrenade_Subsong0_Track19, AHarmlessGrenade_Subsong0_Track21
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd18
; The tracks.

; Pattern 18
	db 1	; State byte.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart19
	dw AHarmlessGrenade_Subsong0_Track24, AHarmlessGrenade_Subsong0_Track19, AHarmlessGrenade_Subsong0_Track21
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd19
; The tracks.

; Pattern 19
	db 13	; State byte.
	db 15	; New height.
	db 2, 0, 2	; The transpositions.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart20
	dw AHarmlessGrenade_Subsong0_Track24, AHarmlessGrenade_Subsong0_Track19, AHarmlessGrenade_Subsong0_Track21
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd20
; The tracks.

; Pattern 20
	db 13	; State byte.
	db 3	; New height.
	db 0, 2, 0	; The transpositions.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart21
	dw AHarmlessGrenade_Subsong0_Track22, AHarmlessGrenade_Subsong0_Track23, AHarmlessGrenade_Subsong0_Track25
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd21
; The tracks.

; Pattern 21
	db 9	; State byte.
	db 0, 10, 4	; The transpositions.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart22
	dw AHarmlessGrenade_Subsong0_Track22, AHarmlessGrenade_Subsong0_Track23, AHarmlessGrenade_Subsong0_Track25
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd22
; The tracks.

; Pattern 22
	db 9	; State byte.
	db 0, 20, 8	; The transpositions.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart23
	dw AHarmlessGrenade_Subsong0_Track22, AHarmlessGrenade_Subsong0_Track23, AHarmlessGrenade_Subsong0_Track25
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd23
; The tracks.

; Pattern 23
	db 9	; State byte.
	db 0, 36, 14	; The transpositions.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart24
	dw AHarmlessGrenade_Subsong0_Track22, AHarmlessGrenade_Subsong0_Track23, AHarmlessGrenade_Subsong0_Track25
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd24
; The tracks.

	db 0	; End of the subsong.
AHarmlessGrenade_Subsong0DisarkPointerRegionStart25
	dw AHarmlessGrenade_Subsong0loop
AHarmlessGrenade_Subsong0DisarkPointerRegionEnd25

; The Tracks.
AHarmlessGrenade_Subsong0_Track0
	db 191, 23	; Escaped note: 23.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 63, 23	; Escaped note: 23.
	db 2	; Note: 26.
	db 5	; Note: 29.
	db 8	; Note: 32.
	db 11	; Note: 35.
	db 5	; Note: 29.
	db 0	; Note: 24.
	db 2	; Note: 26.

AHarmlessGrenade_Subsong0_Track1
	db 61, 31	; Long wait: 32.


AHarmlessGrenade_Subsong0_Track2
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 0	; Reset + inverted volume.
	db 192	; Note: 24.
	db 6	; New instrument: 3.
	db 131	; Volume + possible Pitch up/down.
	db 64	; Note: 24.
	db 128	; Volume + possible Pitch up/down.
	db 64	; Note: 24.
	db 131	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 8	; New instrument: 4.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 6	; New instrument: 3.
	db 130	; Volume + possible Pitch up/down.
	db 64	; Note: 24.
	db 131	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 10	; New instrument: 5.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 6	; New instrument: 3.
	db 130	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 8	; New instrument: 4.
	db 131	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 12	; New instrument: 6.
	db 131	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 8	; New instrument: 4.
	db 133	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 12	; New instrument: 6.
	db 130	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 6	; New instrument: 3.
	db 130	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 8	; New instrument: 4.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 6	; New instrument: 3.
	db 131	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 8	; New instrument: 4.
	db 130	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 10	; New instrument: 5.
	db 131	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 8	; New instrument: 4.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 6	; New instrument: 3.
	db 129	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 10	; New instrument: 5.
	db 131	; Volume + possible Pitch up/down.
	db 64	; Note: 24.
	db 132	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 6	; New instrument: 3.
	db 132	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 8	; New instrument: 4.
	db 130	; Volume + possible Pitch up/down.
	db 128	; Note: 24.
	db 12	; New instrument: 6.

AHarmlessGrenade_Subsong0_Track3
	db 255, 79	; Escaped note: 79.
	db 14	; New instrument: 7.
	db 61, 6	; Long wait: 7.

	db 63, 77	; Escaped note: 77.
	db 61, 6	; Long wait: 7.

	db 63, 72	; Escaped note: 72.
	db 61, 6	; Long wait: 7.

	db 63, 76	; Escaped note: 76.
	db 61, 6	; Long wait: 7.


AHarmlessGrenade_Subsong0_Track4
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 0	; Reset + inverted volume.
	db 190	; Short wait: 3.

	db 255, 75	; Escaped note: 75.
	db 14	; New instrument: 7.
	db 61, 6	; Long wait: 7.

	db 47	; Note: 71.
	db 61, 6	; Long wait: 7.

	db 63, 77	; Escaped note: 77.
	db 61, 6	; Long wait: 7.

	db 63, 79	; Escaped note: 79.
	db 190	; Short wait: 3.


AHarmlessGrenade_Subsong0_Track5
	db 191, 23	; Escaped note: 23.
	db 16	; New instrument: 8.
	db 61, 30	; Long wait: 31.


AHarmlessGrenade_Subsong0_Track6
	db 203	; Note: 35.
	db 20	; New instrument: 10.
	db 0	; Reset + inverted volume.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 61, 5	; Long wait: 6.

	db 191, 23	; Escaped note: 23.
	db 20	; New instrument: 10.
	db 11	; Note: 35.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 11	; Note: 35.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 61, 7	; Long wait: 8.


AHarmlessGrenade_Subsong0_Track7
	db 255, 23	; Escaped note: 23.
	db 24	; New instrument: 12.
	db 0	; Reset + inverted volume.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 61, 5	; Long wait: 6.

	db 255, 23	; Escaped note: 23.
	db 24	; New instrument: 12.
	db 127, 23	; Escaped note: 23.
	db 128	; Volume + possible Pitch up/down.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 62	; Short wait: 1.

	db 63, 23	; Escaped note: 23.
	db 60	; No note, effects only.
	db 127	; Pitch down: 8192.
	dw 8192	; Pitch.
	db 61, 7	; Long wait: 8.


AHarmlessGrenade_Subsong0_Track8
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 0	; Reset + inverted volume.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 62	; Short wait: 1.

	db 144	; Note: 40.
	db 18	; New instrument: 9.
	db 80	; Note: 40.
	db 129	; Volume + possible Pitch up/down.
	db 80	; Note: 40.
	db 130	; Volume + possible Pitch up/down.
	db 80	; Note: 40.
	db 131	; Volume + possible Pitch up/down.
	db 80	; Note: 40.
	db 132	; Volume + possible Pitch up/down.
	db 80	; Note: 40.
	db 133	; Volume + possible Pitch up/down.
	db 80	; Note: 40.
	db 134	; Volume + possible Pitch up/down.
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 128	; Volume + possible Pitch up/down.
	db 0	; Note: 24.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 61, 8	; Long wait: 9.


AHarmlessGrenade_Subsong0_Track9
	db 191, 21	; Escaped note: 21.
	db 20	; New instrument: 10.
	db 62	; Short wait: 1.

	db 66	; Note: 26.
	db 61, 28	; Long wait: 29.


AHarmlessGrenade_Subsong0_Track10
	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 190	; Short wait: 3.

	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 61, 23	; Long wait: 24.


AHarmlessGrenade_Subsong0_Track11
	db 191, 21	; Escaped note: 21.
	db 24	; New instrument: 12.
	db 62	; Short wait: 1.

	db 66	; Note: 26.
	db 61, 28	; Long wait: 29.


AHarmlessGrenade_Subsong0_Track12
	db 191, 19	; Escaped note: 19.
	db 20	; New instrument: 10.
	db 62	; Short wait: 1.

	db 60	; No note, effects only.
	db 127	; Pitch down: 4096.
	dw 4096	; Pitch.
	db 62	; Short wait: 1.

	db 63, 16	; Escaped note: 16.
	db 61, 26	; Long wait: 27.


AHarmlessGrenade_Subsong0_Track13
	db 192	; Note: 24.
	db 4	; New instrument: 2.
	db 0	; Reset + inverted volume.
	db 190	; Short wait: 3.

	db 0	; Note: 24.
	db 204	; Note: 36.
	db 8	; New instrument: 4.
	db 131	; Volume + possible Pitch up/down.
	db 204	; Note: 36.
	db 12	; New instrument: 6.
	db 129	; Volume + possible Pitch up/down.
	db 204	; Note: 36.
	db 6	; New instrument: 3.
	db 130	; Volume + possible Pitch up/down.
	db 61, 23	; Long wait: 24.


AHarmlessGrenade_Subsong0_Track14
	db 191, 19	; Escaped note: 19.
	db 24	; New instrument: 12.
	db 62	; Short wait: 1.

	db 60	; No note, effects only.
	db 127	; Pitch down: 4096.
	dw 4096	; Pitch.
	db 62	; Short wait: 1.

	db 63, 16	; Escaped note: 16.
	db 61, 26	; Long wait: 27.


AHarmlessGrenade_Subsong0_Track15
	db 143	; Note: 39.
	db 28	; New instrument: 14.
	db 61, 4	; Long wait: 5.

	db 12	; Note: 36.
	db 61, 8	; Long wait: 9.

	db 134	; Note: 30.
	db 16	; New instrument: 8.
	db 61, 4	; Long wait: 5.

	db 3	; Note: 27.
	db 61, 8	; Long wait: 9.


AHarmlessGrenade_Subsong0_Track16
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 62	; Short wait: 1.

	db 0	; Note: 24.
	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 190	; Short wait: 3.

	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 126	; Short wait: 2.

	db 0	; Note: 24.
	db 62	; Short wait: 1.

	db 0	; Note: 24.
	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 190	; Short wait: 3.

	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 0	; Note: 24.

AHarmlessGrenade_Subsong0_Track17
	db 216	; Note: 48.
	db 26	; New instrument: 13.
	db 4	; Reset + inverted volume.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 31	; Note: 55.
	db 62	; Short wait: 1.

	db 34	; Note: 58.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 88	; Note: 48.
	db 131	; Volume + possible Pitch up/down.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 30	; Note: 54.
	db 62	; Short wait: 1.

	db 34	; Note: 58.
	db 62	; Short wait: 1.

	db 97	; Note: 57.
	db 130	; Volume + possible Pitch up/down.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 30	; Note: 54.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.


AHarmlessGrenade_Subsong0_Track18
	db 131	; Note: 27.
	db 22	; New instrument: 11.
	db 61, 4	; Long wait: 5.

	db 0	; Note: 24.
	db 61, 8	; Long wait: 9.

	db 63, 18	; Escaped note: 18.
	db 61, 4	; Long wait: 5.

	db 63, 15	; Escaped note: 15.
	db 61, 8	; Long wait: 9.


AHarmlessGrenade_Subsong0_Track19
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 32	; New instrument: 16.
	db 24	; Note: 48.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 32	; New instrument: 16.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 152	; Note: 48.
	db 32	; New instrument: 16.
	db 24	; Note: 48.
	db 24	; Note: 48.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 34	; New instrument: 17.
	db 24	; Note: 48.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 34	; New instrument: 17.
	db 24	; Note: 48.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 34	; New instrument: 17.
	db 152	; Note: 48.
	db 36	; New instrument: 18.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 36	; New instrument: 18.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 152	; Note: 48.
	db 36	; New instrument: 18.
	db 152	; Note: 48.
	db 38	; New instrument: 19.
	db 24	; Note: 48.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 38	; New instrument: 19.
	db 140	; Note: 36.
	db 18	; New instrument: 9.
	db 128	; Note: 24.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 38	; New instrument: 19.
	db 128	; Note: 24.
	db 4	; New instrument: 2.

AHarmlessGrenade_Subsong0_Track20
	db 216	; Note: 48.
	db 30	; New instrument: 15.
	db 2	; Reset + inverted volume.
	db 62	; Short wait: 1.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.

	db 126	; Short wait: 2.


AHarmlessGrenade_Subsong0_Track21
	db 216	; Note: 48.
	db 14	; New instrument: 7.
	db 194	; Reset + inverted volume + Arpeggio Table.
	db 1	; Arpeggio number.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 31	; Note: 55.
	db 62	; Short wait: 1.

	db 34	; Note: 58.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 30	; Note: 54.
	db 62	; Short wait: 1.

	db 34	; Note: 58.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 24	; Note: 48.
	db 62	; Short wait: 1.

	db 27	; Note: 51.
	db 62	; Short wait: 1.

	db 30	; Note: 54.
	db 62	; Short wait: 1.

	db 33	; Note: 57.
	db 62	; Short wait: 1.


AHarmlessGrenade_Subsong0_Track22
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 61, 30	; Long wait: 31.


AHarmlessGrenade_Subsong0_Track23
	db 228	; Note: 60.
	db 20	; New instrument: 10.
	db 127	; Pitch down: 20480.
	dw 20480	; Pitch.
	db 61, 30	; Long wait: 31.


AHarmlessGrenade_Subsong0_Track24
	db 195	; Note: 27.
	db 2	; New instrument: 1.
	db 0	; Reset + inverted volume.
	db 3	; Note: 27.
	db 4	; Note: 28.
	db 4	; Note: 28.
	db 6	; Note: 30.
	db 7	; Note: 31.
	db 0	; Note: 24.
	db 0	; Note: 24.
	db 0	; Note: 24.
	db 0	; Note: 24.
	db 0	; Note: 24.
	db 0	; Note: 24.
	db 4	; Note: 28.
	db 0	; Note: 24.
	db 7	; Note: 31.
	db 0	; Note: 24.
	db 6	; Note: 30.
	db 6	; Note: 30.
	db 6	; Note: 30.
	db 6	; Note: 30.
	db 8	; Note: 32.
	db 9	; Note: 33.
	db 3	; Note: 27.
	db 3	; Note: 27.
	db 3	; Note: 27.
	db 3	; Note: 27.
	db 3	; Note: 27.
	db 2	; Note: 26.
	db 1	; Note: 25.
	db 0	; Note: 24.
	db 63, 23	; Escaped note: 23.
	db 63, 22	; Escaped note: 22.

AHarmlessGrenade_Subsong0_Track25
	db 255, 72	; Escaped note: 72.
	db 24	; New instrument: 12.
	db 61, 30	; Long wait: 31.


AHarmlessGrenade_Subsong0DisarkByteRegionEnd0
