; Song Untitled, in AKY version 1.0, generated by Arkos Tracker 2.

winner_Subsong0
winner_Subsong0DisarkGenerateExternalLabel

; Header
winner_Subsong0DisarkByteRegionStart0
	db 128	; Format version: 0 and endianness: little-endian.
	db 3	; How many channels are encoded.
; Frequency of the PSG index 0: 1000000Hz.
	db 64, 66, 15, 0
winner_Subsong0DisarkByteRegionEnd0

winner_Subsong0_Linker
winner_Subsong0DisarkPointerRegionStart1
; Pattern 0
winner_Subsong0DisarkWordForceNonReference2
	dw 160	; Duration in frames.
	dw winner_Subsong0_Track_0
	dw winner_Subsong0_Track_1
	dw winner_Subsong0_Track_2

; Pattern 1
winner_Subsong0_LinkerLoop	; Loops here.
winner_Subsong0DisarkWordForceNonReference3
	dw 160	; Duration in frames.
	dw winner_Subsong0_Track_5
	dw winner_Subsong0_Track_5
	dw winner_Subsong0_Track_5

winner_Subsong0DisarkWordForceNonReference4
	dw 0	; Loops (duration = 0).
	dw winner_Subsong0_LinkerLoop
winner_Subsong0DisarkPointerRegionEnd1

; The tracks.
winner_Subsong0_Track_0
winner_Subsong0DisarkByteRegionStart5
	db 40	; Duration.
winner_Subsong0DisarkByteRegionEnd5
winner_Subsong0DisarkPointerRegionStart6
	dw winner_Subsong0_RegisterBlock_0
winner_Subsong0DisarkPointerRegionEnd6

winner_Subsong0DisarkByteRegionStart7
	db 40	; Duration.
winner_Subsong0DisarkByteRegionEnd7
winner_Subsong0DisarkPointerRegionStart8
	dw winner_Subsong0_RegisterBlock_1
winner_Subsong0DisarkPointerRegionEnd8

winner_Subsong0DisarkByteRegionStart9
	db 40	; Duration.
winner_Subsong0DisarkByteRegionEnd9
winner_Subsong0DisarkPointerRegionStart10
	dw winner_Subsong0_RegisterBlock_2
winner_Subsong0DisarkPointerRegionEnd10

winner_Subsong0DisarkByteRegionStart11
	db 20	; Duration.
winner_Subsong0DisarkByteRegionEnd11
winner_Subsong0DisarkPointerRegionStart12
	dw winner_Subsong0_RegisterBlock_3
winner_Subsong0DisarkPointerRegionEnd12

winner_Subsong0DisarkByteRegionStart13
	db 20	; Duration.
winner_Subsong0DisarkByteRegionEnd13
winner_Subsong0DisarkPointerRegionStart14
	dw winner_Subsong0_RegisterBlock_4
winner_Subsong0DisarkPointerRegionEnd14

winner_Subsong0_Track_1
winner_Subsong0DisarkByteRegionStart15
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd15
winner_Subsong0DisarkPointerRegionStart16
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd16

winner_Subsong0DisarkByteRegionStart17
	db 5	; Duration.
winner_Subsong0DisarkByteRegionEnd17
winner_Subsong0DisarkPointerRegionStart18
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd18

winner_Subsong0DisarkByteRegionStart19
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd19
winner_Subsong0DisarkPointerRegionStart20
	dw winner_Subsong0_RegisterBlock_8
winner_Subsong0DisarkPointerRegionEnd20

winner_Subsong0DisarkByteRegionStart21
	db 5	; Duration.
winner_Subsong0DisarkByteRegionEnd21
winner_Subsong0DisarkPointerRegionStart22
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd22

winner_Subsong0DisarkByteRegionStart23
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd23
winner_Subsong0DisarkPointerRegionStart24
	dw winner_Subsong0_RegisterBlock_8
winner_Subsong0DisarkPointerRegionEnd24

winner_Subsong0DisarkByteRegionStart25
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd25
winner_Subsong0DisarkPointerRegionStart26
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd26

winner_Subsong0DisarkByteRegionStart27
	db 5	; Duration.
winner_Subsong0DisarkByteRegionEnd27
winner_Subsong0DisarkPointerRegionStart28
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd28

winner_Subsong0DisarkByteRegionStart29
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd29
winner_Subsong0DisarkPointerRegionStart30
	dw winner_Subsong0_RegisterBlock_8
winner_Subsong0DisarkPointerRegionEnd30

winner_Subsong0DisarkByteRegionStart31
	db 5	; Duration.
winner_Subsong0DisarkByteRegionEnd31
winner_Subsong0DisarkPointerRegionStart32
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd32

winner_Subsong0DisarkByteRegionStart33
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd33
winner_Subsong0DisarkPointerRegionStart34
	dw winner_Subsong0_RegisterBlock_8
winner_Subsong0DisarkPointerRegionEnd34

winner_Subsong0DisarkByteRegionStart35
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd35
winner_Subsong0DisarkPointerRegionStart36
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd36

winner_Subsong0DisarkByteRegionStart37
	db 5	; Duration.
winner_Subsong0DisarkByteRegionEnd37
winner_Subsong0DisarkPointerRegionStart38
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd38

winner_Subsong0DisarkByteRegionStart39
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd39
winner_Subsong0DisarkPointerRegionStart40
	dw winner_Subsong0_RegisterBlock_8
winner_Subsong0DisarkPointerRegionEnd40

winner_Subsong0DisarkByteRegionStart41
	db 5	; Duration.
winner_Subsong0DisarkByteRegionEnd41
winner_Subsong0DisarkPointerRegionStart42
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd42

winner_Subsong0DisarkByteRegionStart43
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd43
winner_Subsong0DisarkPointerRegionStart44
	dw winner_Subsong0_RegisterBlock_8
winner_Subsong0DisarkPointerRegionEnd44

winner_Subsong0DisarkByteRegionStart45
	db 40	; Duration.
winner_Subsong0DisarkByteRegionEnd45
winner_Subsong0DisarkPointerRegionStart46
	dw winner_Subsong0_RegisterBlock_21
winner_Subsong0DisarkPointerRegionEnd46

winner_Subsong0_Track_2
winner_Subsong0DisarkByteRegionStart47
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd47
winner_Subsong0DisarkPointerRegionStart48
	dw winner_Subsong0_RegisterBlock_35
winner_Subsong0DisarkPointerRegionEnd48

winner_Subsong0DisarkByteRegionStart49
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd49
winner_Subsong0DisarkPointerRegionStart50
	dw winner_Subsong0_RegisterBlock_24
winner_Subsong0DisarkPointerRegionEnd50

winner_Subsong0DisarkByteRegionStart51
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd51
winner_Subsong0DisarkPointerRegionStart52
	dw winner_Subsong0_RegisterBlock_35
winner_Subsong0DisarkPointerRegionEnd52

winner_Subsong0DisarkByteRegionStart53
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd53
winner_Subsong0DisarkPointerRegionStart54
	dw winner_Subsong0_RegisterBlock_26
winner_Subsong0DisarkPointerRegionEnd54

winner_Subsong0DisarkByteRegionStart55
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd55
winner_Subsong0DisarkPointerRegionStart56
	dw winner_Subsong0_RegisterBlock_27
winner_Subsong0DisarkPointerRegionEnd56

winner_Subsong0DisarkByteRegionStart57
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd57
winner_Subsong0DisarkPointerRegionStart58
	dw winner_Subsong0_RegisterBlock_26
winner_Subsong0DisarkPointerRegionEnd58

winner_Subsong0DisarkByteRegionStart59
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd59
winner_Subsong0DisarkPointerRegionStart60
	dw winner_Subsong0_RegisterBlock_35
winner_Subsong0DisarkPointerRegionEnd60

winner_Subsong0DisarkByteRegionStart61
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd61
winner_Subsong0DisarkPointerRegionStart62
	dw winner_Subsong0_RegisterBlock_24
winner_Subsong0DisarkPointerRegionEnd62

winner_Subsong0DisarkByteRegionStart63
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd63
winner_Subsong0DisarkPointerRegionStart64
	dw winner_Subsong0_RegisterBlock_31
winner_Subsong0DisarkPointerRegionEnd64

winner_Subsong0DisarkByteRegionStart65
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd65
winner_Subsong0DisarkPointerRegionStart66
	dw winner_Subsong0_RegisterBlock_32
winner_Subsong0DisarkPointerRegionEnd66

winner_Subsong0DisarkByteRegionStart67
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd67
winner_Subsong0DisarkPointerRegionStart68
	dw winner_Subsong0_RegisterBlock_31
winner_Subsong0DisarkPointerRegionEnd68

winner_Subsong0DisarkByteRegionStart69
	db 10	; Duration.
winner_Subsong0DisarkByteRegionEnd69
winner_Subsong0DisarkPointerRegionStart70
	dw winner_Subsong0_RegisterBlock_24
winner_Subsong0DisarkPointerRegionEnd70

winner_Subsong0DisarkByteRegionStart71
	db 40	; Duration.
winner_Subsong0DisarkByteRegionEnd71
winner_Subsong0DisarkPointerRegionStart72
	dw winner_Subsong0_RegisterBlock_35
winner_Subsong0DisarkPointerRegionEnd72

winner_Subsong0_Track_5
winner_Subsong0DisarkByteRegionStart73
	db 160	; Duration.
winner_Subsong0DisarkByteRegionEnd73
winner_Subsong0DisarkPointerRegionStart74
	dw winner_Subsong0_RegisterBlock_37
winner_Subsong0DisarkPointerRegionEnd74


; The RegisterBlocks.
winner_Subsong0DisarkByteRegionStart75
winner_Subsong0_RegisterBlock_37
	db 0	; Initial State: no software, no hardware.

winner_Subsong0_RegisterBlock_37_Loop
	db 4	; Non-initial State, no software no hardware.

	db 8	; Loop to index 1.
winner_Subsong0DisarkPointerRegionStart76
	dw winner_Subsong0_RegisterBlock_37_Loop
winner_Subsong0DisarkPointerRegionEnd76


winner_Subsong0_RegisterBlock_0
	db 121	; Initial State: software only.
	db 222, 1	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

winner_Subsong0_RegisterBlock_0_Loop
	db 225	; Non-initial State, software only.
	db 222	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 239	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
winner_Subsong0DisarkPointerRegionStart77
	dw winner_Subsong0_RegisterBlock_0_Loop
winner_Subsong0DisarkPointerRegionEnd77


winner_Subsong0_RegisterBlock_1
	db 121	; Initial State: software only.
	db 102, 1	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

winner_Subsong0_RegisterBlock_1_Loop
	db 225	; Non-initial State, software only.
	db 102	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
winner_Subsong0DisarkPointerRegionStart78
	dw winner_Subsong0_RegisterBlock_1_Loop
winner_Subsong0DisarkPointerRegionEnd78


winner_Subsong0_RegisterBlock_2
	db 121	; Initial State: software only.
	db 63, 1	; Software period.

	db 61	; Non-initial State, software only.

	db 253	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 61	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 249	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 57	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 245	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 53	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 241	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 49	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 237	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 45	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 233	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 41	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

	db 229	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 37	; Non-initial State, software only.

winner_Subsong0_RegisterBlock_2_Loop
	db 225	; Non-initial State, software only.
	db 63	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 225	; Non-initial State, software only.
	db 159	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 33	; Non-initial State, software only.

	db 8	; Loop to index 28.
winner_Subsong0DisarkPointerRegionStart79
	dw winner_Subsong0_RegisterBlock_2_Loop
winner_Subsong0DisarkPointerRegionEnd79


winner_Subsong0_RegisterBlock_21
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 222, 1	; Software period.

	db 241	; Non-initial State, software only.
	db 206	; New LSB for software period.
	db 129	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 158	; New LSB for software period.
	db 193	; New MSB for software period, maybe with noise.
	db 15	; New noise.

	db 8
winner_Subsong0DisarkPointerRegionStart80
	dw winner_Subsong0_RegisterBlock_37 + 1	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd80

winner_Subsong0_RegisterBlock_35
	db 113	; Initial State: software only.
	db 60, 0	; Software period.

	db 57	; Non-initial State, software only.

	db 57	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 53	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 49	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 41	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 37	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 1	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 33	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 29	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 25	; Non-initial State, software only.

	db 8
winner_Subsong0DisarkPointerRegionStart81
	dw winner_Subsong0_RegisterBlock_37 + 1	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd81

winner_Subsong0_RegisterBlock_3
	db 121	; Initial State: software only.
	db 239, 0	; Software period.

	db 61	; Non-initial State, software only.

	db 125	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 61	; Non-initial State, software only.

	db 121	; Non-initial State, software only.
	db 239	; New LSB for software period.

	db 57	; Non-initial State, software only.

	db 121	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 57	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 239	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 117	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 53	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 239	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 113	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 49	; Non-initial State, software only.

	db 109	; Non-initial State, software only.
	db 239	; New LSB for software period.

	db 45	; Non-initial State, software only.

	db 109	; Non-initial State, software only.
	db 119	; New LSB for software period.

	db 45	; Non-initial State, software only.


winner_Subsong0_RegisterBlock_4
	db 81	; Initial State: software only.
	db 243, 0	; Software period.

	db 105	; Non-initial State, software only.
	db 247	; New LSB for software period.

	db 105	; Non-initial State, software only.
	db 131	; New LSB for software period.

	db 105	; Non-initial State, software only.
	db 135	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 3	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 101	; Non-initial State, software only.
	db 7	; New LSB for software period.

	db 229	; Non-initial State, software only.
	db 147	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 101	; Non-initial State, software only.
	db 151	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 19	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 23	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 163	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 167	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 35	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 39	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 179	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 183	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 51	; New LSB for software period.
	db 1	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 55	; New LSB for software period.

	db 225	; Non-initial State, software only.
	db 195	; New LSB for software period.
	db 0	; New MSB for software period, maybe with noise.

	db 97	; Non-initial State, software only.
	db 199	; New LSB for software period.


winner_Subsong0_RegisterBlock_6
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 222, 1	; Software period.

	db 8
winner_Subsong0DisarkPointerRegionStart82
	dw winner_Subsong0_RegisterBlock_21 + 4	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd82

winner_Subsong0_RegisterBlock_8
	db 101	; Initial State: software only.
	db 1	; Noise.
	db 239, 0	; Software period.

	db 241	; Non-initial State, software only.
	db 223	; New LSB for software period.
	db 128	; New MSB for software period, maybe with noise.

	db 233	; Non-initial State, software only.
	db 175	; New LSB for software period.
	db 192	; New MSB for software period, maybe with noise.
	db 15	; New noise.

	db 8
winner_Subsong0DisarkPointerRegionStart83
	dw winner_Subsong0_RegisterBlock_37 + 1	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd83

winner_Subsong0_RegisterBlock_23
	db 113	; Initial State: software only.
	db 60, 0	; Software period.

	db 8
winner_Subsong0DisarkPointerRegionStart84
	dw winner_Subsong0_RegisterBlock_35 + 3	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd84

winner_Subsong0_RegisterBlock_24
	db 113	; Initial State: software only.
	db 80, 0	; Software period.

	db 8
winner_Subsong0DisarkPointerRegionStart85
	dw winner_Subsong0_RegisterBlock_35 + 3	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd85

winner_Subsong0_RegisterBlock_26
	db 113	; Initial State: software only.
	db 53, 0	; Software period.

	db 8
winner_Subsong0DisarkPointerRegionStart86
	dw winner_Subsong0_RegisterBlock_35 + 3	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd86

winner_Subsong0_RegisterBlock_27
	db 113	; Initial State: software only.
	db 47, 0	; Software period.

	db 8
winner_Subsong0DisarkPointerRegionStart87
	dw winner_Subsong0_RegisterBlock_35 + 3	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd87

winner_Subsong0_RegisterBlock_31
	db 113	; Initial State: software only.
	db 89, 0	; Software period.

	db 8
winner_Subsong0DisarkPointerRegionStart88
	dw winner_Subsong0_RegisterBlock_35 + 3	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd88

winner_Subsong0_RegisterBlock_32
	db 113	; Initial State: software only.
	db 95, 0	; Software period.

	db 8
winner_Subsong0DisarkPointerRegionStart89
	dw winner_Subsong0_RegisterBlock_35 + 3	; Optimization: goto common Block at index 1.
winner_Subsong0DisarkPointerRegionEnd89

winner_Subsong0DisarkByteRegionEnd75
